:lang: ja
:doctype: book
:toc: left
:toclevels: 3
:toc-title: 目次
:sectnumlevels: 4s
:icons: font
:source-highlighter: coderay
:example-caption: 例
:table-caption: 表
:figure-caption: 図
:xrefstyle: short
:docname: = Masato MIYATA, Curriculum Vitae
:revdate: 2018/12/17

== 宮田 征門（Masato MIYATA）

=== 略歴
* 1980年2月	福井県あわら市生まれ、兵庫県神戸市育ち
* 1998年3月 兵庫県立兵庫高等学校 卒業
* 2003年3月	京都大学工学部建築学科 卒業
* 2005年3月	京都大学大学院工学研究科 修士課程 修了
* 2008年3月	京都大学大学院工学研究科 博士後期課程 修了/博士(工学) 授与
* 2008年4月	独立行政法人日本学術振興会 特別研究員(PD) (九州大学大学院)
* 2009年4月	独立行政法人建築研究所 建築環境グループ　研究員
* 2014年4月 国土交通省国土技術政策総合研究所 建築研究部 環境・設備基準研究室 主任研究官
* 2015年4月 国土交通省国土技術政策総合研究所 住宅研究部 建築環境研究室 主任研究官（現在に至る）

=== 博士論文
* 空調システムのモデルベースによる検証と最適化に関する研究 => https://repository.kulib.kyoto-u.ac.jp/dspace/bitstream/2433/57288/1/D_Miyata_Masato.pdf[京都大学学術情報リポジトリ]

=== 主な研究テーマ
* 建築設備システムの省エネルギー
** 非住宅建築物の省エネルギー基準のための一次エネルギー消費量の計算手法の開発 → https://github.com/MasatoMiyata[github]
** 個別分散型空調システムの入出力特性の実態解明
* 建築設備のコミッショニング
** シミュレーションを活用した建築設備の性能検証・運用最適化
** 建築と設備の相互作用を考慮した空調システムの運転最適化
** 地中熱等の未利用エネルギーを利用した空調システムの性能検証と運転最適化

=== 受賞歴
. 平成27年度国土交通省国土技術研究会 一般部門（活力）優秀賞「建築物の省エネルギー設計を誘導するエネルギー消費性能予測ツールの開発」, 宮田征門, 2015.11.13
. Best Paper Award of Asim2014 (The 2nd Asia Conference of International Building Performance Simulation Association), Masato MIYATA, 2014.11.29
. 空気調和・衛生工学会賞 学術論文部門, 「コミッショニングのための冷却コイル特性実験とモデル精度の検証」, 山口弘雅、吉田治典、丹羽英治、渡邊剛、宮田征門、小田久人、塩谷正樹, 2012.5.15
. 空気調和・衛生工学会賞 技術論文部門, 「空調用熱源システムの部分負荷運転制御法の開発と導入効果の検証」, 松下直幹、李霽憲、吉田健一、赤司泰義、住吉大輔、宮田征門、田中誠、藤村昌弘, 2012.5.15
. 空気調和・衛生工学会賞 学術論文部門, 「コミッショニングのための複数VAVユニットの不具合検知・診断手法」, 宮田征門，吉田治典，浅田昌彦，橋口士朗, 2008.5.13
. 空気調和・衛生工学会賞 技術賞/技術開発部門, 「杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの開発と実証」, 青野政信，竹川忠克，名倉義行，小林陽一，金政秀，吉田治典，宮田征門, 2008.5.13

=== 科研費(ID:40554986)・助成金
. 文部科学省科学研究費 若手研究(B)-研究代表者, 処理熱量の偏在による効率低下を考慮したマルチ形エアコンの設計評価技術の開発, 2017-2020 
. 文部科学省科学研究費 基盤研究(A)-研究分担者, 熱交換換気システムのための透明性の高い評価設計技術の構築, 2014-2017
. 文部科学省科学研究費 特別研究員奨励費 研究活動スタート支援, 建築と設備の相互作用を考慮した動的計画法による空調システムの運転最適化, 2008-2010
. 財団法人関西エネルギー・リサイクル科学研究振興財団，平成19年度国際交流活動助成（研究者海外渡航）, 2007 

=== 所属学会
* https://www.aij.or.jp/[一般社団法人 日本建築学会]
* http://www.shasej.org/[公益社団法人 空気調和・衛生工学会]

=== 委員会活動
. ISO/TC205/WG10 "Commissioning" 主査 (第一期: 2014-2017) (第二期: 2017-2021)
. 空気調和衛生工学会 コミッショニング委員会
. 日本建築学会 学会誌編集委員会 委員, 2016-2017


=== 研究業績

==== 学術論文
. Eisuke Togashi, Masato Miyata: Development of building thermal environment emulator to evaluate the performance of the HVAC system operation, Journal of Building Performance Simulation, 2019, https://doi.org/10.1080/19401493.2019.1601259[DOI]
. Masato Miyata: Energy efficiency evaluation of multiple split-system air conditioners with unbalanced load operation for building energy simulation, Earth and Environmental Science, Vol.238, 2019, https://doi.org/10.1088/1755-1315/238/1/012082[DOI]
. Fukada Ken, Masato Miyata: Validation of Unsteady CFD considering Thermal Load Fluctuation in Office Room, Vol.238, 2019, https://doi.org/10.1088/1755-1315/238/1/012033[DOI]
. Natascha Milesi Ferretti, Masato Miyata, Oliver Baumann: A retrospective on the impact of Annex 40 and Annex 47 research on the international state of building commissioning, Energy and Buildings 158, p54–61, 2018
. Napoleon ENTERIA, Hideki YAMAGUCHI, Masato MIYATA, Takao SAWACHI, Yasuo KUWASAWA: Performance evaluation of the variable refrigerant flow (VRF) air-conditioning system during the heating-defrosting cyclic operation, Journal of Thermal Science and Technology, Vol.12, No.2, 2017
. Napoleon ENTERIA, Hideki YAMAGUCHI, Masato MIYATA, Takao SAWACHI, Yasuo KUWASAWA: Performance evaluation of the variable refrigerant flow (VRF) air-conditioning system subjected to partial loadings at different outdoor air temperatures, Journal of Thermal Science and Technology, Vol.11, No.2, 2016
. Napoleon ENTERIA, Hideki YAMAGUCHI, Masato MIYATA, Takao SAWACHI, Yasuo KUWASAWA: Performance evaluation of the variable refrigerant flow (VRF) air-conditioning system subjected to partial and unbalanced thermal loadings, Journal of Thermal Science and Technology, Vol.11, No.1, 2016
. 宮田征門、吉田治典、他5名：季間蓄熱機能を有する空調システムのシミュレーションを利用したコミッショニング　第2報 運用開始後3年間に亘る運転最適化プロセス、空気調和衛生工学会論文集、No.218、pp.19-29、2015
. Masato Miyata、et.al.：Web-based simulation tool for compliance with 2013 energy efficiency standard for commercial buildings in Japan, Building Simulation, pp.1766-1773, 2015
. 西澤繁毅、宮田征門、et.al.：改正建築省エネルギー基準に対応した日よけ効果係数算出ツールの開発、日本建築学会技術報告集、第21巻 第49号、pp.1111-1116、2015
. 松下直幹，李霽憲，吉田健一，赤司泰義，住吉大輔，宮田征門，田中誠，藤村昌弘：空調用熱源システムの部分負荷運転制御法の開発と導入効果の検証，空気調和衛生工学会論文集, No.164 , pp.39-48，2010. 11
. 山口弘雅，吉田治典，丹羽英治，渡邊剛，宮田征門，小田久人，塩谷正樹：コミッショニングのための冷却コイル特性実験とモデル精度の検証，空気調和・衛生工学会論文集，pp.61-70，No.143，2009. 2
. 金政秀，安岡稔弘，竹川忠克，名倉義行，小林陽一，吉田治典，宮田征門：季間蓄熱機能を有する空調システムのシミュレーションを利用したコミッショニング，第1報 土壌蓄熱空調システムの開発と初期性能評価，空気調和衛生工学会論文集, No.149 , pp.1-9，2009. 8
. M. Miyata, H. Yoshida, T. Iwata, Z. Zhang, Y. Tanabe, T. Yanagisawa: Application and Verification of Energy Baseline Estimation Method by Simulation, Building Simulation, pp.1968-1974, 2007.9
. M. Miyata, H. Yoshida, T. Yasuoka, T. Takegawa, Y. Nagura, Y. Kobayashi, J. Kim: Optimal Operation for HVAC System with Seasonal Underground Thermal Storage System, Building Simulation, pp.1991-1998, 2007.9
. 宮田征門，吉田治典，浅田昌彦，岩田卓郎，田邊陽一，柳澤忠宏：実ESCOプロジェクトにおけるベースライン簡易補正手法の比較検討，空気調和・衛生工学会論文集，pp.7-16，No.119，2007. 2
. M. Miyata, H. Yoshida, M. Asada, T. Iwata, Y. Tanabe, T. Yanagisawa: Estimation of Energy Baseline by Simulation for On-going Commissioning and Energy Saving Retrofit, Journal of Harbin Institute of Technology, vol.13, pp.370-378, 2006.11
. H. Yamaguchi, M. Miyata, H. Oda, M. Shioya, T. Watanabe, H. Niwa, H. Yoshida: Experimental Study of a Cooling Coil and the Validation of its Simulation Model for the Purpose of Commissioning, Journal of Harbin Institute of Technology, Vol. 13, pp.385-392, 2006.11
. 宮田征門，吉田治典，浅田昌彦，橋口士朗：コミッショニングのための複数VAVユニットの不具合検知・診断手法，空気調和・衛生工学会論文集，pp.1～9，No.114，2006. 9
. M. Miyata, H. Yoshida, M. Asada, K. Fujii, S. Hashiguchi: Estimation of Excessive HVAC Energy Consumption due to faulty VAV units, Building Simulation, pp.777-786, 2005.8
. F. Wang, H. Yoshida, M. Miyata: Total Energy Consumption Model of Fan Subsystem Suitable for Continuous Commissioning, ASHRAE Transactions, Vol. 110, pp. 357-364, 2004


==== 国際会議論文
. Masato Miyata, Koji Kurotori, Napoleon Enteria, Hideki Yamaguchi, Takao Sawachi and Yasuo Kuwasawa: Development of Energy Efficiency Estimation Method for Variable Refrigerant Flow Air-Conditioning System with Unbalanced Heat Load Operation, Building Simulation 2019, 2019
. Masato Miyata: Energy Efficiency Evaluation of Multiple Split-System Air Conditioners with Unbalanced Load Operation for Building Energy Simulation, The 4th Asia Conference on International Building Performance Simulation Association, 2018
. Ken Fukada, Masato Miyata: Validation of Unsteady CFD Considering Thermal Load Fluctuation in Office Room, The 4th Asia Conference on International Building Performance Simulation Association, 2018
. Tatsuhito Itou, Daisuke Sumiyoshi, Mikiko Nakamura, Hiroaki Okamoto, Masato Miyata, Yasuo Kuwasawa: Study on Improvement of Energy Performance Evaluation Method about Cogeneration Systems for Buildings, The 4th Asia Conference on International Building Performance Simulation Association, 2018
. M. Miyata、他5名: Web-based Simulation Tool for the 2013 Energy Efficiency Standard for Commercial Buildings in Japan, The 2nd Asia Conference on International Building Performance Simulation Association, 2014
. E. Tanaka, M. Mukai, K. Matusako, Y. Kodera, S. Maeda, Y. Akashi, H. Yoda, T. Watanabe, M. Miyata: Development of Database for Energy Consumption of Non-residential Buildings in Kyushu, the Proceedings of the Yellow Sea Rim International Exchange Meeting on Building Environment and Energy 2009, pp.79-86, 2009. 1
. M. Miyata, H. Yoshida, M. Aono, T. Yasuoka, T. Takegawa, Y. Nagura, Y. Kobayashi, J. Kim: On-going Commissioning of HVAC System with Seasonal Ground Thermal Storage Using Simulation, the Proceedings of the Yellow Sea Rim International Exchange Meeting on Building Environment and Energy 2009, pp.143-154, 2009. 1
. M. Miyata, H. Yoshida, H. Yoshida: Development of an Information Flow Mechanism for Commissioning, International Conference for Enhanced Building Operations, No. 8, pp. 55(1)-55(8), 2008.10
. M. Miyata, H. Yoshida, T. Yasuoka, T. Takegawa, Y. Nagura, Y. Kobayashi, J. Kim: Development of a Simulation Tool for the Commissioning of a HVAC system with Seasonal Thermal Storage, National conference on Building Commissioning, Chicago, 2007.5
. M. Miyata, H. Yoshida, M. Asada, F. Wang, S. Hashiguchi: Fault Detection and Diagnosis Method for VAV Terminal Units, International Conference of Enhanced Building Operation, PF-52, 2004.10
. M. Miyata, F. Wang, H. Yoshida, M. Tsubaki, K. Itou: Experimental Study on Model-based Commissioning Method of VAV Systems in a Real Building, International Conference of Enhanced Building Operation, 2003.10


==== 国内学会発表論文
. 宮田征門、足永靖信：建築物の電力ピーク対策評価システムの開発、日本建築学会大会学術講演梗概集、p.1201-1202、2016
. 宮田征門、他4名：建築物の室内負荷の偏在がビル用マルチパッケージ型空調システムの運転効率に与える影響の解明、日本冷凍空調学会年次大会梗概集、B132-1-4、2015
. M. Miyata、他4名: Improvement of Energy Efficiency of VRF systems through Staggered Arrangement of indoor units in Heating Mode、空気調和・衛生工学会学術講演論文集、第3巻、pp.249-252、2014
. 野田昂志、吉田治典、宮田征門、他3名：ACSES/Cxを用いた空調2次側ポンプ群の台数制御による省エネルギー効果に関する研究、空気調和・衛生工学会学術講演論文集、第8巻、pp.121-124、2013
. 宮田征門、青山博昌、他3名：個別分散型空調システムの室内機千鳥配置による省エネルギー効果、空気調和・衛生工学会学術講演論文集、第3巻、pp.113-116、2013
. 阿部靖則、宮田征門、他8名：空調システム、給湯システムの各種制御手法におけるエネルギー削減効果の実態調査、（その1）〜（その5）、空気調和・衛生工学会学術講演論文集、 pp.1399-1418、2012
. 吉田治典、宮田征門、他2名：新たな省エネ基準策定のための建築設備の使用実態とエネルギー消費実態に関する調査研究、（その4）個別分散型空調システムの入出力特性に関する実態調査、空気調和・衛生工学会学術講演論文集、pp.2405-2408、2011
. 宮田征門、吉田治典、澤地孝男、桑沢保夫：個別分散型空調システムの運用段階における実性能とJIS 試験法による性能の比較、日本建築学会大会学術講演梗概集、pp.1265-1266、2011
. 小寺優貴・赤司泰義・宮田征門・依田浩敏・前田昌一郎・渡辺俊行・村上周三・亀谷茂樹・半澤久・吉野博・下田吉之・村川三郎：民生業務用建築物の年間エネルギー消費原単位の推定
. 田中絵梨香・依田浩敏・前田昌一郎・赤司泰義・渡辺俊行・宮田征門：九州地域における非住宅建築物の環境関連データベースの構築に関する研究　その３　平成20年度調査における調査建物概要とエネルギー・水消費量の実態
. 田中絵梨香・依田浩敏・赤司泰義・宮田征門・前田昌一郎・渡辺俊行：非住宅（民生業務部門）建築物の環境関連データベース構築に関する研究, その35 九州におけるエネルギー・水消費量の実態（平成20年度調査）, 
. 依田浩敏・田中絵梨香・赤司泰義・宮田征門・前田昌一郎・渡辺俊行：非住宅（民生業務部門）建築物の環境関連データベース構築に関する研究, (その34)九州における調査建物概要と省エネルギー対策（平成20年度調査）, 
. 小寺優貴・赤司泰義・宮田征門・依田浩敏・前田昌一郎・渡辺俊行・村上周三・亀谷茂樹・半澤久・吉野博・下田吉之・村川三郎：非住宅（民生業務部門）建築物の環境関連データベース構築に関する研究, (その23) 標準（レベル２）データベース解析結果（平成19年度調査）	
. 宮田征門，澤地孝男，斉藤正文，梅主洋一郎，川瀬貴晴，坂本雄三：業務用建築の年間空調エネルギー消費量簡略計算法の開発，（その４）室負荷から空調システムのエネルギー消費量を推定する手法の枠組み，空気調和・衛生工学会学術講演論文集，pp.2445-2448，2011.9
. 宮田征門，吉田治典，澤地孝男，桑沢保夫：個別分散型空調システムの運用段階における実性能とJIS 試験法による性能の比較，日本建築学会大会学術講演梗概集, pp.1265-1266, 2011.8
. 宮田征門，吉田治典，澤地孝男，桑沢保夫：個別分散型空調システムの実稼働状態における入出力特性計測手法に関する検討，日本建築学会大会学術講演梗概集, pp.1025-1026, 2010.9
. 宮田征門，足永靖信，澤地孝男，桑沢保夫，秦良昌，三浦尚志：低炭素コミュニティ形成のための水素エネルギー活用技術に関する研究（第3報）省エネルギー・省CO2 効果の評価，空気調和・衛生工学会学術講演論文集，pp.197-200，2010.9
. 宮田征門，吉田治典，辻忠男，湯川求，大川和伸，今井和哉：業務用建築物のためのエネルギー消費量評価手法に関する調査研究（その5）個別分散型空調システムの実稼働状態における入出力特性計測手法に関する検討，空気調和・衛生工学会学術講演論文集，pp.1759-1762，2010.9
. 宮田征門，赤司泰義，末吉祥平：建物とのインタラクションを考慮した空調システムの最適運転制御法，日本建築学会大会学術講演梗概集, pp.1083-1084, 2009.8
. 竹川忠克，青野政信，名倉義行，小林陽一，吉田治典，宮田征門，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その７）他施設への適用を仮定した効果検証，日本建築学会大会学術講演梗概集, pp.1103-1104, 2008.9
. 宮田征門，吉田治典，青野政信，竹川忠克，名倉義行，小林陽一，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その６）シミュレーションによる採熱運転法の最適化とその効果の検証，日本建築学会大会学術講演梗概集, pp.1101-1102, 2008.9
. 吉田泰基，吉田治典，宮田征門：コミッショニングのための情報フロー統合メカニズムに関する研究，日本建築学会大会学術講演梗概集, 選抜梗概, pp.1011-1014, 2008.9
. 大曲康仁，吉田治典，宮田征門，三枝隆晴：シミュレーションを用いたVAVシステムの給気温度設定値の最適化，空気調和・衛生工学会学術講演論文集，pp.2199-2202，2008.8
. 張兆明，吉田治典，宮田征門，新宮浩丈，山下植也，田代博一：シミュレーションを用いた空調用例熱源の最適運転設計と運転に関する研究，空気調和・衛生工学会学術講演論文集，pp.1663-1666，2008.8
. 福崎達也，赤司泰義，住吉大輔，宮田征門，桑原康浩，村澤達，上田憲治：高効率化技術を導入した熱源システムの性能評価，（その１）実測結果に基づく性能評価，空気調和・衛生工学会学術講演論文集，pp.1623-1626，2008.8
. 竹川忠克，青野政信，名倉義行，小林陽一，吉田治典，宮田征門，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その６）他施設への適用を仮定した効果検証，空気調和・衛生工学会学術講演論文集，pp.861-864，2008.8
. 宮田征門，吉田治典，青野政信，竹川忠克，名倉義行，小林陽一，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その５）シミュレーションによる採熱運転法の最適化とその効果の検証，空気調和・衛生工学会学術講演論文集，pp.857-860，2008.8
. 宮田征門，吉田治典，青野政信，竹川忠克，名倉義行，小林陽一，金政秀: 地盤を利用した季間蓄熱機能を有する空調システムの運転最適化, 空気調和・衛生工学会九州支部学術研究発表会, pp19-24, 2008. 5
. 青野政信,竹川忠克, 名倉義行, 小林陽一,金政秀, 吉田治典, 宮田征門: 杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析, （その２）運転実績の評価および性能分析, 第42回空気調和・冷凍連合講演会, 2008.4
. 岩田卓郎，吉田治典，宮田征門：熱負荷計算を用いた補正ベースライン推定モデルの構築法に関する研究, 空気調和・衛生工学会近畿支部学術研究発表会, pp53-56, 2008. 3
. 宮田征門，吉田治典，青野政信，竹川忠克，名倉義行，小林陽一，金政秀:土壌を利用した季間空調システムの性能分析，（その３）シミュレーションによる採熱運転法の最適化とその効果の検証, 空気調和・衛生工学会近畿支部学術研究発表会, pp49-52, 2008. 3
. 張兆明,吉田治典,岩田卓郎,宮田征門:実建物を用いたシミュレーションによるベースライン推定法 (第二報)　室温と外気取入量に関する検証，空気調和・衛生工学会学術講演論文集，pp.2277-2280，2007.9
. 岩田卓郎,吉田治典,張兆明,宮田征門:実建物を用いたシミュレーションによるベースライン推定法 (第一報)　推定法検証のための実建物における実験，空気調和・衛生工学会学術講演論文集，pp.2273-2276，2007.9
. 竹川忠克，青野政信，名倉義行，小林陽一，金政秀，宮田征門，吉田治典，李博：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの性能分析，（その４）運転実績の評価および性能分析，空気調和・衛生工学会学術講演論文集，pp.1765-1768，2007.9
. 宮田征門，吉田治典，李博，青野政信，竹川忠克，名倉義行，小林陽一，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの性能分析，（その３）冷却塔ファンのインバータ化に伴う運転の最適化，空気調和・衛生工学会学術講演論文集，pp.1761-1764，2007.9
. 宮田征門，吉田治典，李博，青野政信，竹川忠克，名倉義行，小林 陽一，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その５） シミュレーションによるシステム運転法の最適化，日本建築学会大会学術講演梗概集，D2，pp. 1217～1218，2007.8
. 李博，吉田治典，宮田征門，青野政信，竹川忠克，名倉義行，小林 陽一，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その４） 空調システム機器モデルの構築と検証，日本建築学会大会学術講演梗概集，D2，pp. 1215～1216，2007.8
. 青野政信，竹川忠克，名倉義行，小林 陽一，金政秀，吉田治典，宮田征門，李博：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その３）運転実績の評価および性能分析，日本建築学会大会学術講演梗概集，D2，pp. 1213～1214，2007.8
. 張兆明，吉田治典，宮田征門，岩田卓郎，田邊陽一，柳澤忠宏，実建物を用いたシミュレーションによるベースライン推定手法の検証，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp.81-84．2007.3
. 宮田征門，吉田治典，李博，安岡稔弘，竹川忠克，名倉義行，小林陽一，金政秀，杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの性能分析，（その２）シミュレーションによるシステムの運転方法の検討，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp.77-80，2007.3
. 李博，吉田治典，宮田征門，安岡稔弘，竹川忠克，名倉義行，小林陽一，金政秀，杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの性能分析，（その１）空調システムの性能検証実験とモデル化，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp.73-76，2007.3
. 宮田征門，吉田治典，安岡稔弘，竹川忠克，名倉義行，小林 陽一，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その２） シミュレーションによるシステムの運転方法の検討，日本建築学会大会学術講演梗概集，D2，pp1301-1302，2006. 9
. 安岡稔弘, 竹川忠克, 名倉義行, 小林陽一,金政秀: 杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その１）システム概要および実測結果，日本建築学会大会学術講演梗概集，D2，pp.1299-1300，2006.9
. 小田久人，山口弘雅，宮田征門，塩谷正樹，渡邉剛，丹羽英治，吉田治典，コミッショニングのためのコイル特性実験とモデル精度の検証，空気調和・衛生工学大会論文集，pp.1669-1672，2006.9
. 岩田卓郎，吉田治典，宮田征門，田邊陽一，柳澤忠宏，シミュレーションによるエネルギーベースライン推定手法，空気調和・衛生工学大会論文集，pp.707-710．2006.9
. 宮田征門，吉田治典，安岡稔弘，竹川忠克，名倉義行，小林陽一，金政秀，杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その２）シミュレーションによるシステム運転方法の検討，空気調和・衛生工学大会論文集，pp.267-270，2006.9
. 竹川忠克, 安岡稔弘, 名倉義行, 小林陽一, 金政秀，吉田治典，宮田征門：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その１）システム概要および実測結果，空気調和・衛生工学大会論文集，pp.263-266，2006.9
. 宮田征門，吉田治典，浅田昌彦，岩田卓郎：ESCOのためのシミュレーションによるベースライン補正手法，（第２報）　ベースライン推定モデルによるベースライン補正式の作成，日本建築学会近畿支部研究報告集，第46号，環境系， pp.321-324，2006.6
. 岩田卓郎，吉田治典，宮田征門，浅田昌彦：ESCOのためのシミュレーションによるベースライン補正手法，（第１報）　熱負荷によるエネルギー浪費量の推定，日本建築学会近畿支部研究報告集，第46号，環境系，pp.317-320，2006.6
. 宮田征門，吉田治典，山下健太郎，安岡稔弘，竹川忠克，名倉義行，小林陽一，金政秀：土壌蓄熱を有する空調システムの性能分析，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp.37-40，2006.3
. 浅田昌彦，岩田卓郎，宮田征門，吉田治典，田邊陽一，柳澤忠宏，シミュレーションによるエネルギーベースライン推定手法（第二報）ベースライン推定モデルとベースライン推定式の作成，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp.33-36，2006.3
. 岩田卓郎，浅田昌彦，宮田征門，吉田治典，田邊陽一，柳澤忠宏，シミュレーションによるエネルギーベースライン推定手法（第一報）熱負荷によるエネルギー消費量の推定，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp.29-32，2006.3
. 宮田征門，吉田治典，藤井健太，浅田昌彦，VAVユニットの不具合によるエネルギー浪費の推定手法に関する，日本建築学会大会学術講演梗概集，pp.33-36，2005.9
. 宮田征門，吉田治典，浅田昌彦：VAVユニットの不具合がシステム全体のエネルギー消費量に与える影響に関する研究，（第２報）シミュレーションによるエネルギー浪費量の推定，日本建築学会近畿支部研究報告集，第45号，環境系，pp.329-332，2005.6
. 浅田昌彦，吉田治典，宮田征門：ＶＡＶユニットの不具合がシステム全体のエネルギー消費量に与える影響に関する研究，（第１報）　実験室実験によるエネルギー浪費の分析，日本建築学会近畿支部研究報告集，第45号，環境系，pp.325-328，2005.6
. 浅田昌彦，吉田治典，宮田征門：実建物におけるVAVユニットの不具合検知・診断手法に関する研究，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp.173-176，2005.3
. 宮田征門，吉田治典，浅田昌彦，橋口士朗：VAVユニットの不具合がシステム全体のエネルギー消費量に与える影響に関する研究，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp169-172，2005.3
. 浅田昌彦，吉田治典，宮田征門：大規模建物におけるVAV ユニットの不具合検知・診断手法に関する研究，(第2報)　予冷時データを用いた不具合検知・診断手法の提案と実証，空気調和・衛生工学会学術講演会論文集，pp.831-834，2004.9
. 宮田征門，吉田治典，浅田昌彦：大規模建物におけるVAV ユニットの不具合検知・診断手法に関する研究，(第1報)　安定運転時データを用いた不具合検知・診断手法の提案と実証，空気調和・衛生工学会学術講演会論文集，pp.827-830，2004.9
. 浅田昌彦，吉田治典，宮田征門：VAVシステムの不具合検知・診断手法に関する研究，日本建築学会大会学術講演梗概集，D2，pp.1457-1458，2004.8
. 宮田征門，吉田治典，浅田昌彦：実事務所ビルにおけるVAV システムの不具合検知・診断手法に関する研究，(第2報)　実運転データを用いた不具合検知・診断手法の結果，日本建築学会近畿支部研究報告集，第44号，環境系，pp.269-272，2004.6
. 浅田昌彦，吉田治典，宮田征門：実事務所建物におけるVAVシステムの不具合検知・診断手法に関する研究，（第1報）スミルノフ・グラブス検定を用いた不具合判定手法，日本建築学会近畿支部研究報告集，第44号，環境系，pp.265-268，2004.6.
. 宮田征門，吉田治典，松岡一平：空調二次側システムのモデルベース検証法，空気調和・衛生工学会学術講演会論文集，pp.1249-1252，2003.9
. 宮田征門，吉田治典，松岡一平：空調二次側システムのモデルベース性能検証手法に関する研究，日本建築学会近畿支部研究報告集，第43号，環境系，pp.365-368，2003.6


. 宮田征門,処理熱量の偏在がマルチ型パッケージエアコンの運転効率に与える影響の解明,空気調和・衛生工学会大会学術講演論文集,2018,,ROMBUNNO.I‐11,,20180829
. 石野久彌, 二宮秀與, 郡公子, 大塚雅之, 柳原隆司, 野原文男, 村上周三, 宮田征門, 長井達夫, 秋元孝之, 牧村功,外皮・躯体と設備・機器の総合エネルギーシミュレーションツール「BEST」の開発(その206)全体概要と最近の開発内容,空気調和・衛生工学会大会学術講演論文集,2018,,ROMBUNNO.OS‐16,,20180829
. 湯澤秀樹, 近藤武士, 久保隆太郎, LEE Chee Woo, 原英嗣, 宮田征門,実績値に基づく一次エネルギー消費量算定用WEBプログラムの妥当性に関する検討,空気調和・衛生工学会大会学術講演論文集,2014,9,105,108,20140825
. 野田昂志, 吉田治典, 宮田征門, 柴田克彦, 前田幸輝, 仲井章一,モデルベースによるVAV空調システムの性能検証に関する研究,空気調和・衛生工学会大会学術講演論文集,2014,8,405,408,20140825
. 前田幸輝, 植田俊克, 鈴木正美, 山本誠, 柴田克彦, 菊池健二, 田中法幸, 宮田征門, 五味弘,各種制御が導入された空調・給湯システムのエネルギー消費の実例(その8)局所式給湯システムの実例,空気調和・衛生工学会大会学術講演論文集,2013,9,29,32,20130912
. 宮田征門, 青山博昌, 太田正治, 松井伸樹, 吉田治典,個別分散型空調システムの室内機千鳥配置による省エネルギー効果,空気調和・衛生工学会大会学術講演論文集,2013,3,113,116,20130912
. 増田正夫, 柴田克彦, 倉田昌典, 友田衛, 山本誠, 鈴木康司, 中村真, 宮田征門, 五味弘,各種制御が導入された空調・給湯システムのエネルギー消費の実例(その2)VWV制御システムの実例,空気調和・衛生工学会大会学術講演論文集,2013,9,5,8,20130912
. 橋本翔, 中村真, 仲井章一, 間宮啓介, 柴田克彦, 立野岡誠, 鈴木康司, 宮田征門, 五味弘,各種制御が導入された空調・給湯システムのエネルギー消費の実例(その3)VAV制御システムの実例,空気調和・衛生工学会大会学術講演論文集,2013,9,9,12,20130912
. 川村昌彦, 鈴木康司, 菊池健二, 柴田克彦, 山本誠, 仲井章一, 宮田征門, 五味弘,各種制御が導入された空調・給湯システムのエネルギー消費の実例(その5)熱源制御の実例,空気調和・衛生工学会大会学術講演論文集,2013,9,17,20,20130912
. 宮田征門, 澤地孝男, 五味弘, 柴田克彦, 竹之内元, 植田俊克, 富田弘明, 鈴木康司, 佐々木洋二, 中村真,各種制御が導入された空調・給湯システムのエネルギー消費の実例(その1)調査事業の位置づけと全体概要,空気調和・衛生工学会大会学術講演論文集,2013,9,1,4,20130912
. 植田俊克, 鈴木正美, 前田幸輝, 立野岡誠, 柴田克彦, 鈴木康司, 中村真, 宮田征門, 五味弘,各種制御が導入された空調・給湯システムのエネルギー消費の実例(その4)外気処理システムによる負荷削減の実例,空気調和・衛生工学会大会学術講演論文集,2013,9,13,16,20130912
. 柴田克彦, 倉田昌典, 増田正夫, 友田衛, 小川貴弘, 川村昌彦, 仲井章一, 宮田征門, 五味弘,各種制御が導入された空調・給湯システムのエネルギー消費の実例(その6)蓄熱制御の実例,空気調和・衛生工学会大会学術講演論文集,2013,9,21,24,20130912
. 山田正也, 中村真, 仲井章一, 田中法幸, 柴田克彦, 植田俊克, 鈴木康司, 宮田征門, 五味弘,各種制御が導入された空調・給湯システムのエネルギー消費の実例(その9)給湯システムにおける太陽熱利用・CGS排熱利用の実例,空気調和・衛生工学会大会学術講演論文集,2013,9,33,36,20130912
. 野田昂志, 吉田治典, 宮田征門, 柴田克彦, 前田幸輝, 仲井章一,ACSES/Cxを用いた空調2次側ポンプ群の台数制御による省エネルギー効果に関する研究,空気調和・衛生工学会大会学術講演論文集,2013,8,121,124,20130912
. 菊池健二, 鈴木康司, 川村昌彦, 新野哲也, 柴田克彦, 植田俊克, 田中法幸, 宮田征門, 五味弘,各種制御が導入された空調・給湯システムのエネルギー消費の実例(その7)中央式給湯システムの実例,空気調和・衛生工学会大会学術講演論文集,2013,9,25,28,20130912
. 阿部靖則, 植田俊克, 五味弘, 柴田克彦, 富田弘明, 鈴木康司, 佐々木洋二, 中村真, 澤地孝男, 宮田征門,空調システム,給湯システムの各種制御手法におけるエネルギー削減効果の実態調査(その1)調査の全体概要,空気調和・衛生工学会大会学術講演論文集,2012,2,1399,1402,20120820
. 柴田克彦, 倉田昌典, 植田俊克, 富田弘明, 中村真, 宮田征門, 阿部靖則,空調システム,給湯システムの各種制御手法におけるエネルギー削減効果の実態調査(その2)熱源機器,搬送機器,外気処理システムの制御と給湯システムに係る分類整理,空気調和・衛生工学会大会学術講演論文集,2012,2,1403,1406,20120820
. 植田俊克, 鈴木正美, 前田幸輝, 柴田克彦, 富田弘明, 中村真, 宮田征門, 阿部靖則,空調システム,給湯システムの各種制御手法におけるエネルギー削減効果の実態調査(その5)外気処理システムに関する実運転データ,空気調和・衛生工学会大会学術講演論文集,2012,2,1415,1418,20120820
. 中村真, 仲井章一, 西村英樹, 熊尾隆丈, 植田俊克, 柴田克彦, 富田弘明, 宮田征門, 阿部靖則,空調システム,給湯システムの各種制御手法におけるエネルギー削減効果の実態調査(その4)変風量制御に関する実運転データとその評価,空気調和・衛生工学会大会学術講演論文集,2012,2,1411,1414,20120820
. 鈴木康司, 富田弘明, 川村昌彦, 飯嶋和明, 植田俊克, 柴田克彦, 中村真, 宮田征門, 阿部靖則,空調システム,給湯システムの各種制御手法におけるエネルギー削減効果の実態調査(その3)変流量制御に関する実運転データとその評価,空気調和・衛生工学会大会学術講演論文集,2012,2,1407,1410,20120820
. 吉田治典, 宮田征門, 澤地孝男, 桑沢保夫,新たな省エネ基準策定のための建築設備の使用実態とエネルギー消費実態に関する調査研究(その4)個別分散型空調システムの入出力特性に関する実態調査,空気調和・衛生工学会大会学術講演論文集,2011,3,2409,2412,20110831
. 石川和成, 柳原隆司, 上谷勝洋, 宮田征門, 高草智, 平岡雅哉, 市川徹,新たな省エネ基準策定のための建築設備の使用実態とエネルギー消費実態に関する調査研究(その3)中央熱源方式の空調熱源におけるエネルギー効率の実態,空気調和・衛生工学会大会学術講演論文集,2011,3,2405,2408,20110831
. 猪岡達夫, 澤地孝男, 宮田征門, 宮島賢一, 住吉大輔, 川瀬貴晴, 坂本雄三,業務用建築の年間空調エネルギー消費量簡略計算法の開発(その2)EDDに準拠した日別熱負荷の算定法,空気調和・衛生工学会大会学術講演論文集,2011,3,2437,2440,20110831
. 長井達夫, 川瀬貴晴, 猪岡達夫, 永田明寛, 枡川依士夫, 赤司泰義, 澤地孝男, 宮田征門, 丹羽勝巳, 近藤武士,新たな省エネ基準策定のための建築設備の使用実態とエネルギー消費実態に関する調査研究(その7)内部発熱の実態,空気調和・衛生工学会大会学術講演論文集,2011,3,2421,2424,20110831
. 米澤仁, 柴田克彦, 宮田征門, 相澤直樹, 入部真武, 桑沢保夫,ビル用マルチの超音波流量計を用いた冷媒流量計測に関する検証―外気条件と冷媒充填量の影響―,空気調和・衛生工学会大会学術講演論文集,2011,2,1363,1366,20110831
. 上野嘉夫, 宮田征門, 辻忠男, 松瀬達也, 澤地孝男, 吉田治典,新たな省エネ基準策定のための建築設備の使用実態とエネルギー消費実態に関する調査研究(その5)個別分散型空調システムの使用実態に関する調査,空気調和・衛生工学会大会学術講演論文集,2011,3,2413,2416,20110831
. 丹羽勝巳, 近藤武士, 坂本雄三, 川瀬貴晴, 澤地孝男, 宮田征門,新たな省エネ基準策定のための建築設備の使用実態とエネルギー消費実態に関する調査研究(その9)標準的な年間空調エネルギー消費量の考え方と試算結果,空気調和・衛生工学会大会学術講演論文集,2011,3,2429,2432,20110831
. 上谷勝洋, 柳原隆司, 高草智, 宮田征門, 石川和成, 市川徹,熱源システムの入出力特性データの収集分析(第2報)電気駆動式熱源データの報告,空気調和・衛生工学会大会学術講演論文集,2011,1,341,344,20110831
. 射場本忠彦, 坂本雄三, 柳原隆司, 吉田治典, 井上隆, 川瀬貴晴, 澤地孝男, 桑沢保夫, 宮田征門, 足永靖信,新たな省エネ基準策定のための建築設備の使用実態とエネルギー消費実態に関する調査研究(その2)調査研究の全体概要,空気調和・衛生工学会大会学術講演論文集,2011,3,2401,2404,20110831
. 三木保弘, 吉澤望, 井上隆, 宮田征門, 澤地孝男, 平紘一,新たな省エネ基準策定のための建築設備の使用実態とエネルギー消費実態に関する調査研究(その6)照明設備における省エネルギー制御手法の効果の実態,空気調和・衛生工学会大会学術講演論文集,2011,3,2417,2420,20110831
. 宮島賢一, 澤地孝男, 猪岡達夫, 宮田征門, 川瀬貴晴, 坂本雄三,業務用建築の年間空調エネルギー消費量簡略計算法の開発(その3)非定常負荷推定式の試算,空気調和・衛生工学会大会学術講演論文集,2011,3,2441,2444,20110831
. 近藤武士, 長井達夫, 川瀬貴晴, 坂本雄三, 枡川依士夫, 佐藤正章, 丹羽勝巳, 松縄堅, 宮田征門, 澤地孝男,新たな省エネ基準策定のための建築設備の使用実態とエネルギー消費実態に関する調査研究(その8)標準室使用条件の設定,空気調和・衛生工学会大会学術講演論文集,2011,3,2425,2428,20110831
. 住吉大輔, 宮田征門, 澤地孝男, 猪岡達夫, 川瀬貴晴, 坂本雄三,業務用建築の年間空調エネルギー消費量簡略計算法の開発(その5)蓄熱システムの評価法,空気調和・衛生工学会大会学術講演論文集,2011,3,2449,2452,20110831
. 澤地孝男, 宮田征門, 川瀬貴晴, 坂本雄三,業務用建築の年間空調エネルギー消費量簡略計算法の開発(その1)新たな年間空調エネルギー消費量計算法の枠組みと意義,空気調和・衛生工学会大会学術講演論文集,2011,3,2433,2436,20110831
. 宮田征門, 澤地孝男, 齋藤正文, 梅主洋一郎, 川瀬貴晴, 坂本雄三,業務用建築の年間空調エネルギー消費量簡略計算法の開発(その4)室負荷から空調システムのエネルギー消費量を推定する手法の枠組み,空気調和・衛生工学会大会学術講演論文集,2011,3,2445,2448,20110831
. 石川和成, 柳原隆司, 高草智, 宮田征門, 上谷勝洋, 市川徹,熱源システムの入出力特性データの収集分析(第1報)吸収冷温水発生機データの報告,空気調和・衛生工学会大会学術講演論文集,2011,1,337,340,20110831
. 松下直幹, 吉田健一, LEE Je Hyeon, 藤村昌弘, 田中誠, 宮田征門, 住吉大輔, 赤司泰義,空調用熱源システム運用におけるコミッショニングツールの開発(第4報)熱源0台運転制御の問題点解決のための補助制御法の検討,空気調和・衛生工学会大会学術講演論文集,2010,3,2199,2202,20100812
. 藤村昌弘, 吉田健一, LEE Je Hyeon, 松下直幹, 田中誠, 宮田征門, 住吉大輔, 赤司泰義,空調用熱源システム運用におけるコミッショニングツールの開発(第3報)リアルタイム運用最適化および0台運転制御の効果検証,空気調和・衛生工学会大会学術講演論文集,2010,3,2195,2198,20100812
. 吉澤望, 井上隆, 平紘一, 三木保弘, 宮田征門, 住吉大輔,業務用建築物のためのエネルギー消費量評価手法に関する調査研究(その7)業務用建築物における各種照明制御手法の省エネルギー効果に関する調査,空気調和・衛生工学会大会学術講演論文集,2010,2,1767,1770,20100812
. 宮田征門, 吉田治典, 辻忠男, 湯川求, 大川和伸, 今井和哉,業務用建築物のためのエネルギー消費量評価手法に関する調査研究(その5)個別分散型空調システムの実稼働状態における入出力特性計測手法に関する検討,空気調和・衛生工学会大会学術講演論文集,2010,2,1759,1762,20100812
. 長井達夫, 川瀬貴晴, 猪岡達夫, 永田明寛, 枡川依士夫, 赤司泰義, 宮田征門,業務用建築物のためのエネルギー消費量評価手法に関する調査研究(その9)事務所建物における内部発熱に関する調査概要,空気調和・衛生工学会大会学術講演論文集,2010,2,1775,1778,20100812
. 宮田征門, 足永靖信, 澤地孝男, 桑沢保夫, 秦良昌, 三浦尚志,低炭素コミュニティ形成のための水素エネルギー活用技術に関する研究(第3報)省エネルギー・省CO2効果の評価,空気調和・衛生工学会大会学術講演論文集,2010,1,197,200,20100812
. 瀬川喜章, 小寺優貴, 田中絵梨香, 河野慎平, 赤司泰義, 渡邊俊行, GAO Weijun, 葛隆生, 前田昌一郎, 依田浩敏, 宮田征門,非住宅(民生業務部門)建築物のエネルギー消費量データベース構築に関する研究  九州地域における平成19~21年度調査に基づくエネルギー・水消費量分析,空気調和・衛生工学会大会学術講演論文集,2010,3,2379,2382,20100812
. 田中誠, 松下直幹, 吉田健一, LEE Je Hyeon, 藤村昌弘, 宮田征門, 住吉大輔, 赤司泰義,空調用熱源システム運用におけるコミッショニングツールの開発(第5報)1次ポンプ余剰圧力活用制御の概要と導入効果の検証,空気調和・衛生工学会大会学術講演論文集,2010,3,2203,2206,20100812
. 秦良昌, 足永靖信, 澤地孝男, 桑沢保夫, 宮田征門, 三浦尚志,低炭素コミュニティ形成のための水素エネルギー活用技術に関する研究(第2報)ケーススタディー,空気調和・衛生工学会大会学術講演論文集,2010,1,193,196,20100812
. 足永靖信, 澤地孝男, 桑沢保夫, 宮田征門, 秦良昌, 三浦尚志,低炭素コミュニティ形成のための水素エネルギー活用技術に関する研究(第1報)研究目的と計算方法,空気調和・衛生工学会大会学術講演論文集,2010,1,189,192,20100812
. 射場本忠彦, 坂本雄三, 柳原隆司, 吉田治典, 井上隆, 川瀬貴晴, 澤地孝男, 桑沢保夫, 宮田征門, 足永靖信, 住吉大輔,業務用建築物のためのエネルギー消費量評価手法に関する調査研究(その1)調査概要および総合的な評価指標の検討,空気調和・衛生工学会大会学術講演論文集,2010,2,1743,1746,20100812
. 西澤繁毅, 住吉大輔, 宮田征門, 澤地孝男,中規模建物の中央式空調システムにおけるシステム実働特性の分析と監視用データの検証,空気調和・衛生工学会大会学術講演論文集,2010,2,1311,1314,20100812
. 平紘一, 井上隆, 吉澤望, 三木保弘, 宮田征門, 住吉大輔, 張本和芳, 市原真希,業務用建築物のためのエネルギー消費量評価手法に関する調査研究(その8)タスク・アンビエント照明を採用した業務用建築物における省エネルギー評価,空気調和・衛生工学会大会学術講演論文集,2010,2,1771,1774,20100812
. 石川和成, 柳原隆司, 上谷勝洋, 宮田征門, 高草智, 平岡雅哉, 市川徹,業務用建築物のためのエネルギー消費量評価手法に関する調査研究(その4)中央方式空気調和設備における熱源機器類の入出力特性調査結果,空気調和・衛生工学会大会学術講演論文集,2010,2,1755,1758,20100812
. 上野嘉夫, 吉田治典, 宮田征門, 辻忠男, 松瀬達也,業務用建築物のためのエネルギー消費量評価手法に関する調査研究(その6)個別分散型空調システムの実働特性分析,空気調和・衛生工学会大会学術講演論文集,2010,2,1763,1766,20100812
. 浦山真一, 赤司泰義, KANG Shinae, 小塩真奈美, 川瀬貴晴, 宮田征門,業務用建築物のためのエネルギー消費量評価手法に関する調査研究(その11)事務所建物(九州地区)における内部発熱に関する調査結果,空気調和・衛生工学会大会学術講演論文集,2010,2,1783,1786,20100812
. 近藤武士, 坂本雄三, 澤地孝男, 桑沢保夫, 宮田征門, 湯澤秀樹, 松縄堅,業務用建築物のためのエネルギー消費量評価手法に関する調査研究(その2)評価指標の特性分析および地域区分の検討,空気調和・衛生工学会大会学術講演論文集,2010,2,1747,1750,20100812
. 山下恵, 猪岡達夫, 川瀬貴晴, 宮田征門,業務用建築物のためのエネルギー消費量評価手法に関する調査研究(その12)事務所建物(中部地区)における内部発熱に関する調査結果,空気調和・衛生工学会大会学術講演論文集,2010,2,1787,1790,20100812
. 上谷勝洋, 柳原隆司, 石川和成, 宮田征門, 高草智, 平岡雅哉, 市川徹,業務用建築物のためのエネルギー消費量評価手法に関する調査研究(その3)中央方式空気調和設備の熱源システム入出力特性データの分析方法の検討,空気調和・衛生工学会大会学術講演論文集,2010,2,1751,1754,20100812
. ZHANG Zhaoming, 吉田治典, 宮田征門, 山下植也, 田代博一,モデルベースによる熱回収を有する空調用冷熱源システムの設計と最適制御に関する研究,空気調和・衛生工学会大会学術講演論文集,2009,3,1635,1638,20090818
. LEE Je Hyeon, 松下直幹, 宮田征門, 吉田健一, 赤司泰義, 住吉大輔,空調用熱源システム運用におけるコミッショニングツールの開発(第2報)リアルタイム運用最適化ツールの実装と提案した熱源機器運転台数制御による省エネ効果の検証,空気調和・衛生工学会大会学術講演論文集,2009,2,1371,1374,20090818
. 吉田健一, 松下直幹, 宮田征門, LEE Je Hyeon, 赤司泰義, 住吉大輔,空調用熱源システム運用におけるコミッショニングツールの開発(第1報)リアルタイム運用最適化ツールの概要とシミュレーションによる省エネ効果の推定,空気調和・衛生工学会大会学術講演論文集,2009,2,1367,1370,20090818
. 田中絵梨香, 依田浩敏, 赤司泰義, 前田昌一郎, 宮田征門, 渡辺俊行, 亀谷茂樹, 高口洋人, 半澤久, 吉野博, 奥宮正哉, 下田吉之, 村川三郎,非住宅(民生業務部門)建築物のエネルギー消費量データベース構築に関する研究  大学・研究機関とスポーツ施設の調査結果,空気調和・衛生工学会大会学術講演論文集,2009,2,1163,1166,20090818
. 依田浩敏, 田中絵梨香, 赤司泰義, 宮田征門, 前田昌一郎, 渡辺俊行,非住宅(民生業務部門)建築物のエネルギー消費量データベース構築に関する研究  九州地域における平成20年度調査結果,空気調和・衛生工学会大会学術講演論文集,2009,2,1143,1146,20090818
. 末吉祥平, 赤司泰義, 宮田征門, 福崎達也,オフィスビルにおけるインバータターボ冷凍機の省エネルギー効果,空気調和・衛生工学会大会学術講演論文集,2009,3,1671,1674,20090818
. 大曲康仁, 吉田治典, 宮田征門, 三枝隆晴,シミュレーションを用いたVAVシステムの給気温度設定値の最適化,空気調和・衛生工学会大会学術講演論文集,2008,3,2199,2202,20080808
. 福崎達也, 赤司泰義, 住吉大輔, 宮田征門, 桑原康浩, 村澤達, 上田憲治,高効率化技術を導入した熱源システムの性能評価(第一報)実測結果に基づく性能評価,空気調和・衛生工学会大会学術講演論文集,2008,3,1623,1626,20080808
. ZHANG Zhaoming, 吉田治典, 宮田征門, 新宮浩丈, 山下植也, 田代博一,シミュレーションを用いた空調用冷熱源の最適運転設計と運転に関する研究,空気調和・衛生工学会大会学術講演論文集,2008,3,1663,1666,20080808
. 宮田征門, 青野政信, 名倉義行, KIM Jeongsoo, 吉田治典, 竹川忠克, 小林陽一,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析(その5)シミュレーションによる採熱運転法の最適化とその効果の検証,空気調和・衛生工学会大会学術講演論文集,2008,2,857,860,20080808
. 竹川忠克, 名倉義行, 吉田治典, KIM Jeongsoo, 青野政信, 小林陽一, 宮田征門,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析(その6)他施設への適用を仮定した効果検証,空気調和・衛生工学会大会学術講演論文集,2008,2,861,864,20080808
. ZHANG Zhaoming, 吉田治典, 岩田卓郎, 宮田征門,実建物を用いたシミュレーションによるベースライン推定法(第二報)室温と外気取入量に関する検証,空気調和・衛生工学会大会学術講演論文集,2007,3,2277,2280,20070824
. 青野政信, 竹川忠克, 名倉義行, 小林陽一, KIM Jeongsoo, 吉田治典, 宮田征門, LI Bo,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析(その4)運転実績の評価および性能分析,空気調和・衛生工学会大会学術講演論文集,2007,3,1765,1768,20070824
. 岩田卓郎, 吉田治典, ZHANG Zhaoming, 宮田征門,実建物を用いたシミュレーションによるベースライン推定法(第一報)推定法検証のための実建物における実験,空気調和・衛生工学会大会学術講演論文集,2007,3,2273,2276,20070824
. 宮田征門, 吉田治典, LI Bo, 青野政信, 竹川忠克, 名倉義行, 小林陽一, KIM Jeongsoo,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの性能分析(その3)冷却塔ファンのインバータ化に伴う運転の最適化,空気調和・衛生工学会大会学術講演論文集,2007,3,1761,1764,20070824
. 宮田征門, 吉田治典, 安岡稔弘, 竹川忠克, 名倉義行, 小林陽一, KIM Jeongsoo,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析(その2)シミュレーションによるシステムの運転方法の検討,空気調和・衛生工学会大会学術講演論文集,2006,1,267,270,20060905
. 竹川忠克, 安岡稔弘, 名倉義行, 小林陽一, KIM Jeongsoo, 吉田治典, 宮田征門,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析(その1)システム概要および実測結果,空気調和・衛生工学会大会学術講演論文集,2006,1,263,266,20060905
. 岩田卓郎, 吉田治典, 宮田征門, 田邊陽一, 柳澤忠宏,シミュレーションによるエネルギーベースライン推定手法,空気調和・衛生工学会大会学術講演論文集,2006,1,707,710,20060905
. 小田久人, 山口弘雅, 宮田征門, 塩谷正樹, 渡邊剛, 丹羽英治, 吉田治典,コミッショニングのための冷却コイル特性実験とモデル精度の検証,空気調和・衛生工学会大会学術講演論文集,2006,3,1669,1672,20060905
. 宮田征門, 浅田昌彦, 吉田治典, 橋口士朗,大規模建物におけるVAVユニットの不具合検知・診断手法に関する研究(第1報)安定運転時データを用いた不具合検知・診断手法の提案と実証,空気調和・衛生工学会大会学術講演論文集,2004,2,827,830,20040820
. 浅田昌彦, 宮田征門, 吉田治典, 橋口士朗,大規模建物におけるVAVユニットの不具合検知.診断手法に関する研究(第2報)予冷時データを用いた不具合検知・診断手法の提案と実証,空気調和・衛生工学会大会学術講演論文集,2004,2,831,834,20040820
. 宮田征門, 吉田治典, 松岡一平,空調二次側システムのモデルベース検証法,空気調和・衛生工学会大会学術講演論文集,2003,CD-ROM,1249,1252,20030917


. ZHANG Zhaoming, 吉田治典, 宮田征門, 山下植也, 田代博一,モデルベースによる熱回収を有する空調用冷熱源システムの設計と最適制御に関する研究,空気調和・衛生工学会近畿支部学術研究発表会論文集,38th,,61,64,20090301
. 宮田征門, 吉田治典, 青野政信, 竹川忠克, 名倉義行, 小林陽一, KIM Jeongsoo,土壌を利用した季間空調システムの性能分析(第3報)シミュレーションによる採熱運転法の最適化とその効果の検証,空気調和・衛生工学会近畿支部学術研究発表会論文集,37th,,49,52,20080301
. 岩田卓郎, 吉田治典, 宮田征門,熱負荷計算を用いた補正ベースライン推定モデルの構築法に関する研究,空気調和・衛生工学会近畿支部学術研究発表会論文集,37th,,53,56,20080301
. 宮田征門, 吉田治典, LI Bo, 安岡稔弘, 竹川忠克, 名倉義行, 小林陽一, KIM Jeongsoo,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの性能分析(その2)シミュレーションによるシステムの運転方法の検討,空気調和・衛生工学会近畿支部学術研究発表会論文集,36th,,77,80,20070301
. ZHANG Zhaoming, 吉田治典, 岩田卓郎, 宮田征門, 田邊陽一, 柳澤忠宏,実建物を用いたシミュレーションによるベースライン推定法の検証,空気調和・衛生工学会近畿支部学術研究発表会論文集,36th,,81,84,20070301
. LI Bo, 吉田治典, 宮田征門, 安岡稔弘, 竹川忠克, 名倉義行, 小林陽一, KIM Jeongsoo,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの性能分析(その1)空調システムの性能検証実験とモデル化,空気調和・衛生工学会近畿支部学術研究発表会論文集,36th,,73,76,20070301
. 宮田征門, 吉田治典, 山下健太郎, 安岡稔弘, 竹川忠克, 名倉義行, 小林陽一, 金政秀,土壌蓄熱を有する空調システムの性能分析,空気調和・衛生工学会近畿支部学術研究発表会論文集,35th,,37,40,20060301
. 岩田卓郎, 浅田昌彦, 宮田征門, 吉田治典, 田辺陽一, 柳沢忠宏,シミュレーションによるエネルギーベースライン推定手法(第一報)熱負荷によるエネルギー消費量の推定,空気調和・衛生工学会近畿支部学術研究発表会論文集,35th,,29,32,20060301
. 浅田昌彦, 岩田卓郎, 宮田征門, 吉田治典, 田辺陽一, 柳沢忠宏,シミュレーションによるエネルギーベースライン推定手法(第二報)ベースライン推定モデルとベースライン推定式の作成,空気調和・衛生工学会近畿支部学術研究発表会論文集,35th,,33,36,20060301
. 宮田征門, 吉田治典, 浅田昌彦, 橋口士朗,VAVユニットの不具合がシステム全体のエネルギー消費量に与える影響に関する研究,空気調和・衛生工学会近畿支部学術研究発表会論文集,34th,,169,172,20050301
. 浅田昌彦, 吉田治典, 宮田征門, 橋口士朗,実建物におけるVAVユニットの不具合検知・診断手法に関する研究,空気調和・衛生工学会近畿支部学術研究発表会論文集,34th,,173,176,20050301


. 坂口雄一, 上野貴広, 住吉大輔, 宮田征門,業務用コジェネレーションシステムのエネルギー性能評価プログラムの開発―シミュレーションプログラムの概要と導入効果検証―,空気調和・衛生工学会九州支部研究報告,,23,77‐80,,20160000
. 依田浩敏, 田中絵梨香, 瀬川喜章, 赤司泰義, 高偉俊, 前田昌一郎, 小寺優貴, 河野慎平, 玄姫, 渡邊俊行, 葛隆生, 宮田征門,九州地域における非住宅建築物の環境関連データベース構築に関する研究  その4  平成19~21年度調査に基づくエネルギー・水消費量分析,空気調和・衛生工学会九州支部研究報告,,17,77,80,20100500
. 吉田健一, 李霽憲, 松下直幹, 赤司泰義, 宮田征門, 住吉大輔,大学施設における空調システム運用最適化に関する研究,空気調和・衛生工学会九州支部研究報告,,16,1,4,20090500
. 末吉祥平, 赤司泰義, 宮田征門, 福崎達也,オフィスビルにおける超高効率熱源システムの適用に関する研究  その1  インバータターボ冷凍機の導入効果,空気調和・衛生工学会九州支部研究報告,,16,15,18,20090500
. 小寺優貴, 赤司泰義, 宮田征門, 依田浩敏, 前田昌一郎, 渡辺俊行, 村上周三, 亀谷茂樹, 半澤久, 吉野博, 下田吉之, 村川三郎,民生業務用建築物の年間エネルギー消費原単位の推定,空気調和・衛生工学会九州支部研究報告,,16,77,80,20090500
. 福崎達也, 赤司泰義, 宮田征門, 末吉祥平,オフィスビルにおける超高効率熱源システムの適用に関する研究  その2  最適運用方法による省エネルギー効果,空気調和・衛生工学会九州支部研究報告,,16,19,22,20090500
. LEE Je Hun, 吉田健一, 松下直幹, 赤司泰義, 宮田征門, 住吉大輔,大学施設における熱源機器台数運転制御の省エネルギー効果,空気調和・衛生工学会九州支部研究報告,,16,5,8,20090500
. 杉田匡英, 寺地愛優, 高井智広, 宮田征門, 赤司泰義, 渡辺俊行,都市環境負荷予測シミュレーターの開発  その1  シミュレーターの開発方法,空気調和・衛生工学会九州支部研究報告,,16,63,66,20090500
. 田中絵梨香, 依田浩敏, 前田昌一郎, 赤司泰義, 渡辺俊行, 宮田征門,九州地域における非住宅建築物の環境関連データベースの構築に関する研究  その3  平成20年度調査における調査建物概要・省エネルギー対策とエネルギー・水消費量の実態,空気調和・衛生工学会九州支部研究報告,,16,67,72,20090500
. KANG Shinae, 金栽弘, 赤司泰義, 宮田征門,空調システムシミュレーションを用いた不具合検知・診断手法の開発と検証,空気調和・衛生工学会九州支部研究報告,,16,9,14,20090500
. 寺地愛優, 杉田匡英, 高井智広, 宮田征門, 赤司泰義, 渡辺俊行,福岡市における1975年から2004年までの民生部門のCO<sub>2</sub>排出量の推計,空気調和・衛生工学会九州支部研究報告,,16,73,76,20090500
. 宮田征門, 吉田治典, 青野政信, 竹川忠克, 名倉義行, 小林陽一, 金政秀,地盤を利用した季間蓄熱機能を有する空調システムの運転最適化,空気調和・衛生工学会九州支部研究報告,,15,19,24,20080500


. 石橋直彦, 大野慶祐, 齋藤潔, 山口秀樹, ENTERIA Napoleon, 宮田征門, 澤地孝男,圧縮式ヒートポンプの実運転性能評価法に関する研究―非定常断続運転時のCOP評価―,空気調和・冷凍連合講演会講演論文集,49th,,ROMBUNNO.40,,20150415
. 山口秀樹, ENTERIA Napoleon, 宮田征門, 澤地孝男,個別分散型空調システムの部分負荷運転時における入力特性の検証,空気調和・冷凍連合講演会講演論文集,49th,,ROMBUNNO.37,,20150415
. 米澤仁, 相澤直樹, 柴田克彦, 宮田征門, 桑沢保夫,ビル用マルチの冷媒流量の現地計測に関する可能性試験,空気調和・冷凍連合講演会講演論文集,45th,,133,136,20110418
. 青野政信, 竹川忠克, 名倉義行, 小林陽一, 宮田征門, 吉田治典, 金政秀,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析(その3)他施設への適用を仮定した効果検証,空気調和・冷凍連合講演会講演論文集,43rd,,29,32,20090420
. 安岡稔弘, 竹川忠克, 名倉義行, 小林陽一, 金政秀, 吉田治典, 宮田征門,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析(その1)システム概要および実測結果,空気調和・冷凍連合講演会講演論文集,41st,,53,56,20070417

. 石野久彌, 村上周三, 二宮秀與, 宮田征門, 郡公子, 長井達夫, 大塚雅之, 秋元孝之, 柳原隆司, 牧村功, 野原文男, 滝澤総,建築エネルギー・環境シミュレーションツールBESTの開発  第78報  各種ツールの進展と省エネ傾向の推定,日本建築学会学術講演梗概集,2018,,ROMBUNNO.41487,,20180720
. 木原麻衣, 坂口雄一, 伊藤竜一, 鄭てん, 住吉大輔, 中村美紀子, 岡本洋明, 桑沢保夫, 宮田征門,業務用コージェネレーション設備の性能評価手法の高度化に向けた調査  その4  運転スケジュール分析と設計手法調査,日本建築学会学術講演梗概集,2018,,ROMBUNNO.41665,,20180720
. 伊藤竜一, 木原麻衣, 鄭てん, 坂口雄一, 住吉大輔, 中村美紀子, 岡本洋明, 桑沢保夫, 宮田征門,業務用コージェネレーション設備の性能評価手法の高度化に向けた調査  その6  排熱回収効率及び,排熱投入型吸収式冷温水機の特性分析,日本建築学会学術講演梗概集,2018,,ROMBUNNO.41667,,20180720
. 坂口雄一, 伊藤竜一, 鄭てん, 木原麻衣, 住吉大輔, 中村美紀子, 岡本洋明, 桑沢保夫, 宮田征門,業務用コージェネレーション設備の性能評価手法の高度化に向けた調査  その7  エネルギー消費量の計算方法の構築に向けた検討,日本建築学会学術講演梗概集,2018,,ROMBUNNO.41668,,20180720
. ZHENG Tian, 坂口雄一, 伊藤竜一, 木原麻衣, 住吉大輔, 中村美紀子, 岡本洋明, 桑沢保夫, 宮田征門,業務用コージェネレーション設備の性能評価手法の高度化に向けた調査  その5  起動停止特性と補機動力特性分析,日本建築学会学術講演梗概集,2018,,ROMBUNNO.41666,,20180720
. 坂口雄一, 伊藤竜一, 住吉大輔, 岡本洋明, 中村美紀子, 桑沢保夫, 宮田征門,業務用コージェネレーション設備の性能評価手法の高度化に向けた調査  その2  現場管理状況等把握のためのヒアリング調査,日本建築学会学術講演梗概集,2017,,ROMBUNNO.41553,,20170720
. 伊藤竜一, 坂口雄一, 住吉大輔, 岡本洋明, 中村美紀子, 桑沢保夫, 宮田征門,業務用コージェネレーション設備の性能評価手法の高度化に向けた調査  その3  実測データに基づく性能特性分析,日本建築学会学術講演梗概集,2017,,ROMBUNNO.41554,,20170720
. 岡本洋明, 中村美紀子, 住吉大輔, 坂口雄一, 伊藤竜一, 桑沢保夫, 宮田征門,業務用コージェネレーション設備の性能評価手法の高度化に向けた調査  その1  導入状況および運転状況等の把握のためのアンケート調査,日本建築学会学術講演梗概集,2017,,ROMBUNNO.41552,,20170720
. 坂口雄一, 上野貴広, 住吉大輔, 宮田征門,業務用コジェネレーションシステムのエネルギー性能評価手法の開発―シミュレーションプログラムの概要とスケジュールの標準化―,日本建築学会学術講演梗概集,2016,,ROMBUNNO.41673,,20160720
. 宮田征門, 足永靖信,建築物の電力ピーク対策評価システムの開発,日本建築学会学術講演梗概集,2016,,ROMBUNNO.41567,,20160720
. 西澤繁毅, 宮田征門, 桑沢保夫, 澤地孝男,地中熱ヒートポンプシステムにおける熱源水温度予測モデルに関する検討,日本建築学会学術講演梗概集,2016,,ROMBUNNO.41504,,20160720
. 伊藤聡美, 郷新源, 川瀬貴晴, 永田明寛, 長井達夫, 宮田征門,業務用建物の内部発熱に関する実態調査  その2  教育施設における調査結果,日本建築学会学術講演梗概集,2011,,487,488,20110720
. 宮田征門, 吉田治典, 澤地孝男, 桑沢保夫,個別分散型空調システムの運用段階における実性能とJIS試験法による性能の比較,日本建築学会学術講演梗概集,2011,,1265,1266,20110720
. 今村俊紀, 永田明寛, 長井達夫, 川瀬貴晴, 宮田征門,業務用建物の内部発熱に関する実態調査  その1  ホール・飲食店の調査結果,日本建築学会学術講演梗概集,2011,,485,486,20110720
. 田中絵梨香, 小寺優貴, 河野慎平, 瀬川喜章, XUAN Ji, 赤司泰義, 渡邊俊行, GAO Weijun, 葛隆生, 前田昌一郎, 依田浩敏, 宮田征門,非住宅建築物の環境関連データベース構築に関する研究  その52  九州における平成19~21年度調査に基づくエネルギー・水消費量分析,日本建築学会学術講演梗概集,2010,,1173,1174,20100720
. 宮田征門, 吉田治典, 澤地孝男, 桑沢保夫, 足永靖信,個別分散型空調システムの実稼働状態における入出力特性計測手法に関する検討,日本建築学会学術講演梗概集,2010,,1025,1026,20100720
. 寺地愛優, 杉田匡英, 高井智広, 宮田征門, 赤司泰義, 渡辺俊行,福岡市における1975年から2004年までの民生部門のCO<sub>2</sub>排出量の推計,日本建築学会学術講演梗概集,2009,,815,816,20090720
. 小寺優貴, 赤司泰義, 宮田征門, 依田浩敏, 前田昌一郎, 渡辺俊行, 村上周三, 亀谷茂樹, 半澤久, 吉野博, 下田吉之, 村川三郎,非住宅(民生業務部門)建築物の環境関連データベース構築に関する研究  その23  標準(レベル2)データベース解析結果(平成19年度調査),日本建築学会学術講演梗概集,2009,,1137,1138,20090720
. 田中絵梨香, 依田浩敏, 赤司泰義, 宮田征門, 前田昌一郎, 渡辺俊行,非住宅建築物の環境関連データベース構築に関する研究  その35  九州におけるエネルギー・水消費量の実態について(平成20年度調査),日本建築学会学術講演梗概集,2009,,1161,1162,20090720
. 杉田匡英, 寺地愛優, 高井智広, 宮田征門, 赤司泰義, 渡辺俊行,都市環境負荷予測シミュレーターの開発  その1  シミュレーターの開発手法,日本建築学会学術講演梗概集,2009,,1167,1168,20090720
. 高井智広, 杉田匡英, 寺地愛優, 宮田征門, 赤司泰義, 渡辺俊行,都市環境負荷予測シミュレーターの開発  その2  個別セクターのモデル化,日本建築学会学術講演梗概集,2009,,1169,1170,20090720
. 依田浩敏, 田中絵梨香, 赤司泰義, 宮田征門, 前田昌一郎, 渡辺俊行,非住宅建築物の環境関連データベース構築に関する研究  その34  九州における調査建物概要と省エネルギー対策について(平成20年度調査),日本建築学会学術講演梗概集,2009,,1159,1160,20090720
. 宮田征門, 赤司泰義, 末吉祥平,建物とのインタラクションを考慮した空調システムの最適運転制御法,日本建築学会学術講演梗概集,2009,,1083,1084,20090720
. 福崎達也, 赤司泰義, 宮田征門, 末吉祥平,産業用熱源システムにおける高効率化技術の省エネルギー効果に関する研究,日本建築学会学術講演梗概集,2009,,1217,1220,20090720
. 宮田征門, 吉田治典, 青野政信, 竹川忠克, 名倉義行, 小林陽一, KIM Jeongsoo,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析(その6)シミュレーションによる採熱運転法の最適化とその効果の検証,日本建築学会学術講演梗概集,2008,,1101,1102,20080720
. 吉田泰基, 吉田治典, 宮田征門,コミッショニングのための情報フロー統合メカニズムに関する研究,日本建築学会学術講演梗概集,2008,,1011,1014,20080720
. 竹川忠克, 青野政信, 名倉義行, 小林陽一, 吉田治典, 宮田征門, 金政秀,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析(その7)他施設への適用を仮定した効果検証,日本建築学会学術講演梗概集,2008,,1103,1104,20080720
. 宮田征門, 吉田治典, LI Bo, 青野政信, 竹川忠克, 名倉義行, 小林陽一, KIM Jeongsoo,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの性能分析(その5)シミュレーションによるシステム運転法の最適化,日本建築学会学術講演梗概集,2007,,1217,1218,20070731
. 青野政信, 竹川忠克, 名倉義行, 小林陽一, KIM Jeongsoo, 吉田治典, 宮田征門, LI Bo,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析(その3)運転実績の評価および性能分析,日本建築学会学術講演梗概集,2007,,1213,1214,20070731
. LI Bo, 吉田治典, 宮田征門, 青野政信, 竹川忠克, 名倉義行, 小林陽一, KIM Jeongsoo,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの性能分析(その4)空調システム機器モデルの構築と検証,日本建築学会学術講演梗概集,2007,,1215,1216,20070731
. 宮田征門, 吉田治典, 安岡稔弘, 竹川忠克, 名倉義行, 小林陽一, KIM Jeongsoo,杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析(その2)シミュレーションによるシステムの運転方法の検討,日本建築学会学術講演梗概集,2006,,1301,1302,20060731
. 宮田征門, 吉田治典, 浅田昌彦,VAVユニットの不具合によるエネルギー浪費の推定手法に関する研究,日本建築学会学術講演梗概集,2005,,33,36,20050731
. 浅田昌彦, 吉田治典, 宮田征門,VAVシステムの不具合検知・診断手法に関する研究,日本建築学会学術講演梗概集,2004,,1457,1458,20040731


. 高山紗輝, 赤司泰義, 宮田征門, 福崎達也,オフィスビルにおける高効率化技術の導入効果  その1  インバータターボ冷凍機導入による省エネルギー効果,日本建築学会九州支部研究報告 2 環境系,,49,309,312,20100301
. 福崎達也, 赤司泰義, 宮田征門, 高山紗輝,オフィスビルにおける高効率化技術の導入効果  その2  福岡市を対象とした高効率化技術の普及によるエネルギー消費量削減効果,日本建築学会九州支部研究報告 2 環境系,,49,313,316,20100301
. 河野誉厳, 李霽憲, 吉田健一, 松下直幹, 赤司泰義, 住吉大輔, 宮田征門,リアルタイム運用最適化と熱源機器0台運転制御による省エネ効果の検討,日本建築学会九州支部研究報告 2 環境系,,49,317,320,20100301
. 田中絵梨香, 河野慎平, 小寺優貴, 赤司泰義, 渡辺俊行, 依田浩敏, GAO Weijun, 葛隆生, 前田昌一郎, 宮田征門,九州地域における非住宅建築物のエネルギー消費量データベース構築に関する研究(その8)平成19~21年度の調査結果に基づくエネルギー・水消費量分析,日本建築学会九州支部研究報告 2 環境系,,49,225,228,20100301
. 小塩真奈美, 赤司泰義, 宮田征門, KANG Shinae, 浦山真一,建物空調システム設計が運用時のエネルギー消費量に与える影響,日本建築学会九州支部研究報告 2 環境系,,49,285,288,20100301
. 小寺優貴, 赤司泰義, 宮田征門, 依田浩敏, 前田昌一郎, 渡辺俊行, 村上周三, 亀谷茂樹, 半澤久, 吉野博, 下田吉之, 村川三郎,民生業務用建築物の年間エネルギー消費原単位の推定―非住宅建築物環境関連データベース2007年度調査結果による推定式の作成―,日本建築学会九州支部研究報告 2 環境系,,48,201,204,20090301
. 末吉祥平, 赤司泰義, 宮田征門, 福崎達也,産業用熱源システムの高効率化技術に関する研究  その1  シミュレーションモデルの構築と精度検証,日本建築学会九州支部研究報告 2 環境系,,48,301,304,20090301
. 松迫啓介, 向井美穂子, 田中絵梨香, 小寺優貴, 依田浩敏, 赤司泰義, 宮田征門, 前田昌一郎, 渡辺俊行,九州地域における非住宅建築物のエネルギー消費量データベース構築に関する研究(その4)平成20年度調査における調査建物概要と省エネルギー対策について,日本建築学会九州支部研究報告 2 環境系,,48,209,212,20090301
. 宮田征門, 赤司泰義, 小塩真奈美, 末吉祥平,建物とのインタラクションを考慮した空調システムの最適運転制御法,日本建築学会九州支部研究報告 2 環境系,,48,313,316,20090301
. 福崎達也, 赤司泰義, 宮田征門, 末吉祥平,産業用熱源システムの高効率化技術に関する研究  その2  シミュレーションによる省エネルギー効果の分析,日本建築学会九州支部研究報告 2 環境系,,48,305,308,20090301
. 小塩真奈美, 赤司泰義, 宮田征門,空調システム装置容量が運用時のエネルギー消費量に与える影響,日本建築学会九州支部研究報告 2 環境系,,48,309,312,20090301
. LEE Je Hun, 吉田健一, 赤司泰義, 住吉大輔, 宮田征門,熱源システムのリアルタイム運用最適化ツールの開発  その2  最適化ツールの実装と省エネルギー効果,日本建築学会九州支部研究報告 2 環境系,,48,329,332,20090301
. 吉田健一, 李霽憲, 赤司泰義, 住吉大輔, 宮田征門,熱源システムのリアルタイム運用最適化ツールの開発  その1  シミュレーションモデルの構築と精度検証,日本建築学会九州支部研究報告 2 環境系,,48,325,328,20090301
. 杉田匡英, 高井智広, 赤司泰義, 宮田征門, 渡辺俊行,システムダイナミクスによる都市環境負荷予測シミュレーターの開発  その2  人口セクターと住宅セクター,日本建築学会九州支部研究報告 2 環境系,,48,485,488,20090301
. 向井美穂子, 松迫啓介, 田中絵梨香, 小寺優貴, 依田浩敏, 赤司泰義, 宮田征門, 前田昌一郎, 渡辺俊行,九州地域における非住宅建築物のエネルギー消費量データベース構築に関する研究(その5)平成20年度調査におけるエネルギー・水消費量の実態について,日本建築学会九州支部研究報告 2 環境系,,48,213,216,20090301
. 高井智広, 杉田匡英, 赤司泰義, 宮田征門, 渡辺俊行,システムダイナミクスによる都市環境負荷予測シミュレーターの開発  その1  都市環境負荷予測シミュレーターの開発意義とその手法,日本建築学会九州支部研究報告 2 環境系,,48,481,484,20090301


. 伊藤竜一, 鄭てん, 住吉大輔, 崔榮晋, 中村美紀子, 岡本洋明, 桑沢保夫, 宮田征門,業務用コジェネレーションシステムの性能評価手法の高度化に関する研究(第六報)エネルギー消費量の計算方法の構築及び,省エネルギー効果の検討,日本建築学会研究報告 九州支部,,58,ROMBUNNO.487,,20190301
. 伊藤竜一, 坂口雄一, 鄭てん, 木原麻衣, 住吉大輔, 中村美紀子, 岡本洋明, 桑沢保夫, 宮田征門,業務用コジェネレーションシステムの性能評価手法の高度化に関する研究(第五報)機器効率及び,排熱投入型吸収式冷温水機の特性分析,日本建築学会研究報告 九州支部,,57,ROMBUNNO.440,,20180301
. ZHENG Tian, 坂口雄一, 伊藤竜一, 木原麻衣, 住吉大輔, 中村美紀子, 岡本洋明, 桑沢保夫, 宮田征門,業務用コジェネレーションシステムの性能評価手法の高度化に関する研究(第四報)起動停止特性と補機動力特性分析,日本建築学会研究報告 九州支部,,57,ROMBUNNO.439,,20180301
. 木原麻衣, 坂口雄一, 伊藤竜一, 鄭てん, 住吉大輔, 中村美紀子, 岡本洋明, 桑沢保夫, 宮田征門,業務用コジェネレーションシステムの性能評価手法の高度化に関する研究(第三報)CGS運用スケジュール分析と設計手法調査結果,日本建築学会研究報告 九州支部,,57,ROMBUNNO.438,,20180301
. 伊藤竜一, 坂口雄一, 住吉大輔, 宮田征門, 中村美紀子, 岡本洋明,業務用コジェネレーションシステムの性能評価手法の高度化に関する研究―(第二報)システム及び,機器効率の分析―,日本建築学会研究報告 九州支部,,56,ROMBUNNO.443,,20170000
. 坂口雄一, 伊藤竜一, 住吉大輔, 宮田征門, 中村美紀子, 岡本洋明,業務用コジェネレーションシステムの性能評価手法の高度化に関する研究(第一報)プロジェクト概要とアンケート・ヒアリング結果分析,日本建築学会研究報告 九州支部,,56,ROMBUNNO.442,,20170000
. 坂口雄一, 上野貴広, 住吉大輔, 宮田征門,業務用コジェネレーションシステムの性能評価手法の開発―シミュレーションプログラムの開発と感度解析―,日本建築学会研究報告 九州支部,,55,ROMBUNNO.487,,20160000



. 宮田征門, ENTERIA Napoleon, 山口秀樹, 澤地孝男, 桑沢保夫,建築物の室内負荷の偏在がビル用マルチパッケージ型空調システムの運転効率に与える影響の解明  その3:建築物の一次エネルギー消費量に与える影響の分析,日本冷凍空調学会年次大会講演論文集,2015,,ROMBUNNO.B133,,20150000
. 伴俊憲, 大野慶祐, 齋藤潔, 山口秀樹, 宮田征門, 澤地孝男, ENTERIA Napoleon, 桑沢保夫,圧縮式ヒートポンプの実運転性能評価法に関する研究  断続運転の消費エネルギー推定手法,日本冷凍空調学会年次大会講演論文集,2015,,ROMBUNNO.B123,,20150000
. 山口秀樹, ENTERIA Napoleon, 宮田征門, 澤地孝男, 桑沢保夫,建築物の室内負荷の偏在がビル用マルチパッケージ型空調システムの運転効率に与える影響の解明  その1:実験室実験による運転効率の分析,日本冷凍空調学会年次大会講演論文集,2015,,ROMBUNNO.B131,,20150000
. 山口秀樹, 宮田征門, 澤地孝男, 大野慶祐, 齋藤潔,パッケージ型空調機の圧縮機運転パターンが効率に与える影響,日本冷凍空調学会年次大会講演論文集,2014,,ROMBUNNO.B321,,20140000



==== 学会誌寄稿
. 宮田征門、吉田治典：IEA/ECBCS/Annex40及びAnnex47において実施したコミッショニングの国際的状況に関する調査研究が与えた影響（海外文献紹介）、空気調和・衛生工学 Vol.93、No.6、pp.43-53、2019
. 天野雄一朗, 竹川忠克, 青野政信, 宇草和義, 丸岡政司, 中田紀一, 小林陽一, 安岡稔弘, 小野坂充央, 吉田治典, 赤司泰義, 住吉大輔, 葛隆生, 金政秀, 宮田征門: ヨンデンビル新館のコミッショニングを活用した継続的な省エネルギー・負荷平準化への取組み,空気調和・衛生工学 Vol.89, No.7, pp.599-602,2015
. 宮田征門: 平成26年技術動向 6.情報・コンピュータ利用 6.3 省エネ法の改正に伴う省エネルギー計算・評価ソフトおよび性能表示制度の紹介 6.3.3 建築物省エネルギー性能表示制度(BELS)の概要,空気調和・衛生工学 Vol.88, No.12 ,pp.1246-1248,2014
. 宮田征門: 平成26年技術動向 6.情報・コンピュータ利用 6.3 省エネ法の改正に伴う省エネルギー計算・評価ソフトおよび性能表示制度の紹介 6.3.1 計算支援プログラムおよび補助ツール,空気調和・衛生工学 Vol.88, No.12 ,pp.1241-1243,2014
. 宮田征門: 平成25年技術動向 1.環境 1.1 非住宅建築物の省エネルギー基準の改正,空気調和・衛生工学 Vol.87, No.12 ,pp.1008-1013,2013
. 青野政信, 安岡稔弘, 竹川忠克, 名倉義行, 小林陽一, 吉田治典, 宮田征門, KIM Jeong‐soo: 杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの開発と実証,空気調和・衛生工学 Vol.82, No.7, pp.543-548,2008

==== 業界誌寄稿
. 宮田征門：エネルギー消費性能評価法 -省エネ基準の評価法拡張と評定スキームの構築- 、建築工業調査会 ベース建築資料 No181 建築編、pp.32-35、2019
. 宮田征門：省エネルギー基準評価プログラムの開発 評価法の拡張と新技術評定スキームの構築 、ベターリビング　BLつくば 第22号、2019
. 宮田征門：建築設計・施工関連クラウドサービス 建築物省エネルギー基準への適合性判定プログラム(WEBPRO),建築設備と配管工事 No.57,pp.6‐10, 2019
. 宮田征門：空調制御システムの機能性能試験マニュアルの作成、建築環境省エネルギー機構　機関誌IBEC、Vol40-1、No230、pp.24-28、2019
. 宮田征門,適合義務化された省エネルギー基準の現状と今後の展開,建築設備,69,3,125‐128,,20180301
. 宮田征門,非住宅建築物の新たな環境設計手法を探る  II.省エネ義務化の概要と環境建築  環境建築設計におけるシミュレーションの活用,建築技術,,811,90‐91,,20170717
. 宮田征門,建築物のエネルギー消費性能の向上に関する法律(I)2.新法に関係する省エネルギー性能評価技術に関する現状と動向(1)非住宅建築物, 機関誌IBEC, No.36-5,p10-15,2016
. 宮田征門：基準適合性判定プログラム（非住宅建築物）の開発趣旨、BE建築設備 No.780、pp.14-18、2016
. 宮田征門：建築物省エネ法の現状と今後の展望「エネルギー消費性能計算プログラム」を活用した設計プロセス、BE建築設備 No.789、pp.25-31、2016
. 宮田征門：建築物の省エネ設計の可能性を拓く  III.建築物省エネルギー性能表示制度(BELS)の概要  BELSの評価  概要,建築技術,,800,102‐105,,2016
. 宮田征門：建築物の省エネ設計の可能性を拓く  IV.省エネ建築物でエネルギー削減効果が得られる手法  一次エネルギー消費量による評価  設備機器の性能を活かす選択方法,建築技術,,800,112‐118,,2016
. 宮田征門：建築物省エネ法に向けた省エネ性能評価の設計最前線  基準適合性判定プログラム(非住宅建築物)の開発趣旨,建築設備,67,1,14,18,2016
. 桑沢保夫, 三浦尚志, 宮田征門, 宮田征門, 宮田征門, 赤嶺嘉彦：省エネ評価のプログラムソフト(省エネ評価手法)の開発,建築の研究, Vol.235, pp.13‐17, 2016
. 宮田征門：建築環境設計におけるエネルギーシミュレーションの活用、建築技術 No.786、pp.162-165、2015
. 宮田征門,改正省エネルギー基準の建築環境設計への活用  III.改正省エネルギー基準および設計法に関する動向 非住宅建築物の省エネルギー化のためのガイドライン, 建築技術, No.786, pp.92-97,2015
. 宮田征門,自立循環型住宅研究における研究報告  その2  6.非住宅建築物の省エネルギー化のためのガイドライン, 機関誌IBEC, No.36-4,p29-34,2015
. 宮田征門：改正省エネルギー基準を省エネ設計に活用する（一次エネルギー消費量）、建築技術 No.775、 pp.122-125、2014
. 宮田征門：建築の改正省エネルギー基準と設計への応用：空気調和設備の計算の導き方、建築技術 No.775、pp.96-103、2014
. 宮田征門：建築の改正省エネルギー基準と設計への応用：機械換気設備の計算の導き方、建築技術 No.775、pp.104-107、2014
. 宮田征門,住宅及び建築物の省エネルギー基準の改正(II)4.建築物(4)ポイント法に替わる簡易評価法(モデル建物法), 機関誌IBEC, No.34-5,p44-49,2014
. 宮田征門,住宅及び建築物の省エネルギー基準の改正(II)4.非住宅建築物(3)一次エネルギー消費量計算の簡易入力法(主要室入力法), 機関誌IBEC, No.34-5,p40-43,2014
. 宮田征門：自立循環プロジェクト（フェーズ4）における業務用建築物を対象とした研究の方向性について、建築環境省エネルギー機構　機関誌IBEC、Vol33-4、No193、pp.58-59、2013
. 宮田征門,住宅及び建築物の省エネルギー基準の改正  4.建築物における改正基準の概要(3)一次エネルギー消費量算定プログラムについて, 機関誌IBEC, No.33-6,p53-54,2013
. 猪岡達夫, 宮島賢一, 宮田征門,住宅及び建築物の省エネルギー基準の改正  4.建築物における改正基準の概要(2)2)1  空調設備, 機関誌IBEC, No.33-6,p41-44,2013
. 宮田征門,住宅及び建築物の省エネルギー基準の改正  4.建築物における改正基準の概要(2)1)計算のフロー, 機関誌IBEC, No.33-6,p39-40,2013
. 宮田征門：建築物の省エネルギー基準の見直し、一次エネルギー消費量の算出方法について、BE建築設備、一般社団法人建築設備総合協会、第751号、pp.14-21、2013
. 宮田征門：非住宅建築物の省エネルギー基準の改正、空気調和衛生工学、第87巻第12号、pp.14-21、2013
. 宮田征門,自立循環型住宅研究における研究報告 最新の研究成果の紹介 自立循環プロジェクト(フェーズ4)における業務用建築物を対象とした研究の方向性について, 機関誌IBEC, No.33-4,p58-59,2012
. 宮田征門, 金井昭典,マクロ経済分析を考慮した住宅・建築物の低炭素化に向けた技術の普及方策と政策提言  4.ロードマップ策定に係る研究・調査の解説(5)デルファイ法による低炭素化技術の導入率予測, 機関誌IBEC, No.33-3,p49-56,2012
. 金井昭典, 宮田征門,マクロ経済分析を考慮した住宅・建築物の低炭素化に向けた技術の普及方策と政策提言  4.ロードマップ策定に係る研究・調査の解説(3)低炭素化技術の導入バリアに関する調査, 機関誌IBEC, No.33-3,p36-41,2012


==== 出版物（共著）
. 公益財団法人日本建築衛生管理教育センター著：新建築物の環境生成管理（下巻）、9.3 コミッショニング、p273-277、2019
. 平成28年省エネルギー基準に準拠した算定・判断の方法及び解説、国土技術政策総合研究所・建築研究所監修、2017
. 平成25年省エネルギー基準に準拠した算定・判断の方法及び解説(I.非住宅建築物、第二版)、国土技術政策総合研究所・建築研究所監修、2014
. 平成25年省エネルギー基準に準拠した算定・判断の方法及び解説(I.非住宅建築物)、国総研・建研監修、2013

==== 公開研究資料
. 国総研資料第1081号： 空調・換気設備の自動制御システムを対象としたエネルギー消費性能試験法に関する検討
. 建築研究資料第191号: 業務用コージェネレーション設備の性能評価手法の高度化に関する研究, H30.04
. 建築研究資料第190号: 各種空調設備システムの潜熱負荷処理メカニズムを踏まえたエネルギー消費量評価法に関する検討 , H30.04
. 建築研究資料第187号: 建築物の設備・機器のエネルギー効率に関する既存試験方法の調査, H29.09
. 国総研資料第974号, 建築研究資料第183号: 平成28年省エネルギー基準（平成28年1月公布）関係技術資料 モデル建物法入力支援ツール解説, H29.06
. 国総研資料第973号, 建築研究資料第182号: 平成28年省エネルギー基準（平成28年1月公布）関係技術資料 エネルギー消費計算プログラム（非住宅版）解説, H29.06
. 建築研究資料第177号: 業務用空調・給湯システムの制御による省エネルギー効果の実証的評価 H28.11
. 建築研究資料第176号: 業務用建築物のエネルギー消費量評価手法に関する基礎的調査, H28.11
. 国総研プロジェクト研究報告第53号: 電力依存度低減に資する建築物の評価・設計技術の開発, H28.11
. 建築研究資料第164号: 住宅･建築物省CO2先導事業全般部門(平成22年度～24年度)における採択事例の評価分析, H27.02
. 建築研究資料第161号: 開口部の日射熱取得性能および断熱性能の評価方法, 2014
. 建築研究資料第155号: 集合住宅の住まい方・設備保有状況に関する基礎調査, 2014
. 国総研資料第764号, 建築研究資料第151号: 平成25年省エネルギー基準(平成25年9月公布)等関係技術資料 主要室入力法による非住宅建築物の一次エネルギー消費量算定プログラム解説, H25.11
. 国総研資料第763号, 建築研究資料第150号: 平成25年省エネルギー基準(平成25年9月公布)等関係技術資料 非住宅建築物の外皮性能評価プログラム解説, H25.11
. 国総研資料第762号, 建築研究資料第149号: 平成25年省エネルギー基準(平成25年9月公布)等関係技術資料 一次エネルギー消費量算定プログラム解説(非住宅建築物編), H25.11
. 国総研資料第702号, 建築研究資料第140号: 低炭素建築物認定基準(平成24年12月公布)等関係技術資料 一次エネルギー消費量算定プログラム解説(建築物編), H24.12


==== 学内報・所内報等
. 三木保弘, 宮田征門, 山口秀樹,オフィスの昼光利用による年間の照明エネルギー削減効果の評価法開発,国総研レポート,,17,170,,20180400
. 宮田征門, 三木保弘,先進的な建築物のエネルギー消費性能評価技術の開発,国総研レポート,,17,168,,20180400
. 三木保弘, 赤嶺嘉彦, 宮田征門, 桑沢保夫,建築物のエネルギー消費性能の向上を目指したファサード設計法に関する研究,国総研レポート,,17,169,,20180400
. 伊藤竜一, 住吉大輔, 中村美紀子, 岡本洋明, 宮田征門, 桑沢保夫: 業務用コージェネレーション設備の性能評価手法に関する研究―運転状況の把握と実働性能の評価―,都市・建築学研究, NO.34, pp.13‐20, 2018
. 澤地孝男, 三木保弘, 宮田征門, 赤嶺嘉彦,建築物省エネ性能に係わる国際規格の動向と国総研の取り組み(研究期間:平成18年度~),国総研レポート,,16,151,,20170400
. 宮田征門, 三木保弘, 赤嶺嘉彦,建築設備の自動制御技術によるエネルギー削減効果の評価法の開発(研究期間:平成28~30年度),国総研レポート,,16,157,,20170400
. 三木保弘, 赤嶺嘉彦, 宮田征門,建築物のエネルギー消費性能の向上を目指したファサード設計法に関する研究(研究期間:平成29~31年度),国総研レポート,,16,158,,20170400
. 宮田征門,非住宅建築物の省エネ設計を誘導するエネルギー消費性能予測ツールの開発と実証実験,国総研レポート,,14,115,,20150400
. 澤地孝男, 三浦尚志, 赤嶺嘉彦, 宮田征門,非住宅建築物における外皮性能の新たな評価指標,国総研レポート,,14,119,,20150400
. 桑沢保夫, 澤地孝男, 瀬戸宏尚, 宮田征門, 山口秀樹, 牧野清, 荻野登司, 佐瀬毅,省エネ基準運用強化に向けた住宅・建築の省エネルギー性能評価手法の高度化,建築研究所年報,2013,,5,6,20140630
. 岩田司, 加藤真司, 内田晃, 桑澤保夫, 宮田征門,アジアの蒸暑地域に対応した低炭素型戸建住宅設計技術に関する研究,建築研究所年報,2013,,37,38,20140630
. 澤地孝男, 桑沢保夫, 三木保弘, 宮田征門, 三浦尚志,建築の省エネ性能評価と設計法の今後―既存技術の向上と普及に向けた革新的技術開発の重要性―,独立行政法人建築研究所講演会,2013,,67,78,20140000
. 桑沢保夫, 澤地孝男, 宮田征門,住宅・建築の更なる省エネルギー化,独立行政法人建築研究所講演会,2012,,19,30,20130308
. 宮田征門,業務用建築設備のエネルギー消費実態に関する研究,独立行政法人建築研究所講演会,2011,,83,84,20120309
. 宮田征門,蓄エネルギーを考慮した街区エネルギー需給ネットワークの運転最適化に関する研究【基盤】,建築研究所年報,2011,,9,10,20120629
. 宮田征門,運営費交付金による研究開発  2)環境研究グループ  2)―3  住宅の外皮性能と暖冷房設備を統合した設計方法の構築【基盤】,建築研究所年報,2010,,15,16,20110630
. 宮田征門,外部資金による研究開発  3)科学研究費補助金  3)―3  建築と設備の相互作用を考慮した動的計画法による空調システムの運転最適化,建築研究所年報,2010,,65,66,20110630
. 桑沢保夫, 瀬戸裕直, 住吉大輔, 宮田征門, 齋藤宏昭, 河野孝昭, 牧野清, SHI Ting, 荻野登司, 海老名將,運営費交付金による研究開発  2)環境研究グループ  2)―1  建築・コミュニティーのライフサイクルにわたる低炭素化のための技術開発【個別重点】,建築研究所年報,2010,,11,12,20110630
. 姜信愛，赤司泰義，宮田征門，小塩真奈美，浦山真一：建物空調システム設計が運用時のエネルギー消費量に与える影響，都市・建築学研究 九州大学大学院人間環境学研究院紀要，No.17， pp.55-61，2010
. 李霽憲，赤司泰義，住吉大輔，宮田征門，松下直幹：熱源システムのリアルタイム運転最適化手法の開発と実建物への適用，都市・建築学研究　九州大学大学院人間環境学研究院紀要，No.15， pp.103-110，2009
. 松下直幹, LEE Je Hyeon, 吉田健一, 赤司泰義, 住吉大輔, 宮田征門: 大学施設における空調用熱源システムのコミッショニング,都市・建築学研究 九州大学大学院人間環境学研究院紀要, No.16, pp.119-124, 2009



=== 依頼/招待講演・講義
. 建築とITのフォーラム 2019 建築フォーラム　人と建築の未来をデザインする -建築ピボット EXPO 2019- : 省エネルギー建築の現在と未来, 2019.10.9（東京）
. グリーンビルディングフォーラム(GBF)-IBEC 第10回シンポジウム 2050年に向けた住宅・建築物のエネルギー政策: 建築物のネットゼロ化に向けた国内外の建築規制・対策, 2019.8.29（東京）
. 建築物省エネ法に関する算定ロジックと計算事例解説（一般財団法人建築環境・省エネルギー機構）, 2018.11.16（東京）, 2018.12.19（東京）
. 東京大学 環境調整工学特論 2018年度： 建築物のエネルギー消費性能の定量的評価, 2018.6.26
. イオンリテール イオン下妻店（出前講座） : たてものでつかう エネルギー, 2018.8.6
. 第26回地中熱利用シンポジウム: 建築物省エネルギー基準における地中熱利用ヒートポンプの評価法, 2018.3.14
. 第31回公衆衛生情報研究協議会研究会: 適合義務化された建築物省エネルギー基準の現状と今後の展開, 2018.1.25
. 一般財団法人建築環境・省エネルギー機構 主催：平成27年度省エネルギー基準の「算定・判断方法に係る根拠・理論」の説明会, H27.7.17（東京）, H27.7.30（大阪）
. 放射(輻射)冷暖房協議会・ASHRAE JAPAN Chapter 共催セミナー: 省エネ基準適合義務化の施行状況と今後のビジョン, 2017.9.11
. 長野県地中熱利用促進協議会: 省エネ基準適合義務化の概要と地中熱ヒートポンプの評価法, 2017.6.21
. ENEX2017 地中熱セミナー: 省エネ基準適合義務化の概要と地中熱ヒートポンプの評価法, 2017.2.17
. 中部地中熱利用促進協議会地中熱設計セミナー: 省エネ基準適合義務化の概要と地中熱ヒートポンプの評価法, 2017.2.10
. 地中熱利用促進協会 地中熱利用にかかる省エネ基準説明会: 省エネ基準適合義務化の概要と地中熱ヒートポンプの評価法, 2016.12.16
. 建築環境設計支援協会 CFDシンポジウム: 建築物の省エネルギー基準と建築環境シミュレーション (エネルギーシミュレーション), 2016.5.18, 2016.11.30
. 平成27年度第2回地中熱利用シンポジウム: 省エネ基準適合義務化の背景と地中熱への期待, 2016.3.10
. HVAC&R JAPAN 2016: いよいよ始まる建築物省エネ基準の適合義務化 ~ 建築確認申請における 設備機器の性能確認について ~, 2016.2.24
. 日本設備設計事務所協会 設備設計セミナー: 新法「建築物省エネ基準」の概要 ~ 建築確認申請における性能判定について ~, 2015.10.7
. 東京大学 建築環境特論 2015〜2017年度: 究極の省エネルギー建築物を設計するために必要な3つのこと, 2015.7.10, 2016.5.13, 2017.5.12
. 一般社団法人関西ESCO協会 特別講演会: 住宅・建築物の省エネ化に関する施策の最新情報と今後の展開, 2015.6.8
. 工学院大学 建築学部まちづくり学科 建築学特別講義 2015年度：究極の省エネルギー建築物を設計するために必要な3つのこと, 2015.6.5
. 一般財団法人建築環境・省エネルギー機構 主催：平成26年度建築物の建築物の省エネルギー基準講習会, 2015.1.20（東京）, 2015.2.4（東京）, 2015.2.20（福岡）
. 一般財団法人建築環境・省エネルギー機構 主催：平成26年度省エネルギー基準の「算定・判断方法に係る根拠・理論」の説明会, 2014.9.25（東京）, 2014.10.3（大阪）
. 群馬県設備設計事務所協会 技術研修会: 改正省エネルギー基準（非住宅建築物）の概要と今後の展開, 2014.3.7
. つくばエキスポセンター ミニ講演: 住まいで使うエネルギーについて, 2013.11.23
. 空気調和・衛生工学会近畿支部一般講習会（平成25年度）: 省エネルギー法・新たな建築物省エネ基準の本格運用に向けて, 2013.11.21
. 一般財団法人建築環境・省エネルギー機構 主催：平成25年度省エネルギー基準の「算定・判断方法に係る根拠・理論」の説明会, 2013.10.23（大阪）, 2013.10.30（東京）
. 空気調和・衛生工学会コミッショニングシンポジウム特別講演：省エネ基準の見直しの概要とコミッショニングの役割, 2013.8.9
. つくば市立手代木南小学校（出前講座）: 住まいで使うエネルギー, 2013.7.26
. 空気調和・衛生工学会九州支部講習会'建築物の省エネルギーに関する施策と基準の最新動向': 非住宅建築物の省エネルギー基準の概要, 2013.2.27
. TSC21 オープンセミナー2012 vol.2 'エネルギー施策とマネジメントの動向': 建築物の省エネルギー施策の動向と新たな省エネルギー基準の概要, 2012.12.6
. 空気調和・衛生工学会近畿支部一般講習会（平成24年度）: 建築物の省エネルギー施策の動向と新たな省エネルギー基準の概要,2012.12.4
. 建築設備技術者協会 講習会 '取り組んでみた省エネ手法': ビルの新しい省エネルギー 判断基準の策定にむけて - 空調システムのエネルギー消費量 簡略計算法の概要, 2011.10.26
. 建築設備コミッショニング協会 東京講演会: ビルの新しい省エネルギー判断基準の策定に向けて, 2011.5.19




