:lang: ja
:doctype: book
:toc: left
:toclevels: 3
:toc-title: 目次
:sectnumlevels: 4s
:icons: font
:source-highlighter: coderay
:example-caption: 例
:table-caption: 表
:figure-caption: 図
:xrefstyle: short
:docname: = Masato MIYATA, Curriculum Vitae
:revdate: 2018/12/17

== 宮田 征門（Masato MIYATA）

=== 略歴
* 1980年2月	福井県あわら市生まれ、兵庫県神戸市育ち
* 1998年3月 兵庫県立兵庫高等学校 卒業
* 2003年3月	京都大学工学部建築学科 卒業
* 2005年3月	京都大学大学院工学研究科 修士課程 修了
* 2008年3月	京都大学大学院工学研究科 博士後期課程 修了/博士(工学) 授与
* 2008年4月	独立行政法人日本学術振興会 特別研究員(PD) (九州大学大学院)
* 2009年4月	独立行政法人建築研究所 建築環境グループ　研究員
* 2014年4月 国土交通省国土技術政策総合研究所 建築研究部 環境・設備基準研究室 主任研究官
* 2015年4月 国土交通省国土技術政策総合研究所 住宅研究部 建築環境研究室 主任研究官（現在に至る）

=== 博士論文
* 空調システムのモデルベースによる検証と最適化に関する研究 => https://repository.kulib.kyoto-u.ac.jp/dspace/bitstream/2433/57288/1/D_Miyata_Masato.pdf[京都大学学術情報リポジトリ]

=== 主な研究テーマ
* 建築設備システムの省エネルギー
** 非住宅建築物の省エネルギー基準のための一次エネルギー消費量の計算手法の開発
** 個別分散型空調システムの入出力特性の実態解明
* 建築設備のコミッショニング
** シミュレーションを活用した建築設備の性能検証・運用最適化
** 建築と設備の相互作用を考慮した動的計画法による空調システムの運転最適化
** 地盤を利用した季間蓄熱機能を有する空調システムの性能検証と運転最適化

=== 受賞歴
. 平成27年度国土交通省国土技術研究会 一般部門（活力）優秀賞「建築物の省エネルギー設計を誘導するエネルギー消費性能予測ツールの開発」, 宮田征門, 2015.11.13
. Best Paper Award of Asim2014 (The 2nd Asia Conference of International Building Performance Simulation Association), Masato MIYATA, 2014.11.29
. 空気調和・衛生工学会賞 学術論文部門, 「コミッショニングのための冷却コイル特性実験とモデル精度の検証」, 山口弘雅、吉田治典、丹羽英治、渡邊剛、宮田征門、小田久人、塩谷正樹, 2012.5.15
. 空気調和・衛生工学会賞 技術論文部門, 「空調用熱源システムの部分負荷運転制御法の開発と導入効果の検証」, 松下直幹、李霽憲、吉田健一、赤司泰義、住吉大輔、宮田征門、田中誠、藤村昌弘, 2012.5.15
. 空気調和・衛生工学会賞 学術論文部門, 「コミッショニングのための複数VAVユニットの不具合検知・診断手法」, 宮田征門，吉田治典，浅田昌彦，橋口士朗, 2008.5.13
. 空気調和・衛生工学会賞 技術賞/技術開発部門, 「杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの開発と実証」, 青野政信，竹川忠克，名倉義行，小林陽一，金政秀，吉田治典，宮田征門, 2008.5.13

=== 科研費・助成金
. 文部科学省科学研究費 若手研究(B)-研究代表者, 処理熱量の偏在による効率低下を考慮したマルチ形エアコンの設計評価技術の開発, 2017-2020 
. 文部科学省科学研究費 基盤研究(A)-研究分担者, 熱交換換気システムのための透明性の高い評価設計技術の構築, 2014-2017
. 文部科学省科学研究費 特別研究員奨励費 研究活動スタート支援, 建築と設備の相互作用を考慮した動的計画法による空調システムの運転最適化, 2008-2010
. 財団法人関西エネルギー・リサイクル科学研究振興財団，平成19年度国際交流活動助成（研究者海外渡航）, 2007 

=== 所属学会
* https://www.aij.or.jp/[一般社団法人 日本建築学会]
* http://www.shasej.org/[公益社団法人 空気調和・衛生工学会]


=== 研究業績

==== 学術論文
. Natascha Milesi Ferretti, Masato Miyata, Oliver Baumann: A retrospective on the impact of Annex 40 and Annex 47 research on the international state of building commissioning, Energy and Buildings 158, p54–61, 2018
. Napoleon ENTERIA, Hideki YAMAGUCHI, Masato MIYATA, Takao SAWACHI, Yasuo KUWASAWA: Performance evaluation of the variable refrigerant flow (VRF) air-conditioning system during the heating-defrosting cyclic operation, Journal of Thermal Science and Technology, Vol.12, No.2, 2017
. Napoleon ENTERIA, Hideki YAMAGUCHI, Masato MIYATA, Takao SAWACHI, Yasuo KUWASAWA: Performance evaluation of the variable refrigerant flow (VRF) air-conditioning system subjected to partial loadings at different outdoor air temperatures, Journal of Thermal Science and Technology, Vol.11, No.2, 2016
. Napoleon ENTERIA, Hideki YAMAGUCHI, Masato MIYATA, Takao SAWACHI, Yasuo KUWASAWA: Performance evaluation of the variable refrigerant flow (VRF) air-conditioning system subjected to partial and unbalanced thermal loadings, Journal of Thermal Science and Technology, Vol.11, No.1, 2016
. 宮田征門、吉田治典、他5名：季間蓄熱機能を有する空調システムのシミュレーションを利用したコミッショニング　第2報 運用開始後3年間に亘る運転最適化プロセス、空気調和衛生工学会論文集、No.218、pp.19-29、2015
. Masato Miyata、他5名：WEB-BASED SIMULATION TOOL FOR COMPLIANCE WITH 2013 ENERGY EFFICIENCY STANDARD FOR COMMERCIAL BUILDINGS IN JAPAN, Building Simulation, pp.1766-1773, 2015
. 西澤繁毅、宮田征門、他2名：改正建築省エネルギー基準に対応した日よけ効果係数算出ツールの開発、日本建築学会技術報告集、第21巻 第49号、pp.1111-1116、2015
. 松下直幹，李霽憲，吉田健一，赤司泰義，住吉大輔，宮田征門，田中誠，藤村昌弘：空調用熱源システムの部分負荷運転制御法の開発と導入効果の検証，空気調和衛生工学会論文集, No.164 , pp.39-48，2010. 11
. 山口弘雅，吉田治典，丹羽英治，渡邊剛，宮田征門，小田久人，塩谷正樹：コミッショニングのための冷却コイル特性実験とモデル精度の検証，空気調和・衛生工学会論文集，pp.61-70，No.143，2009. 2
. 金政秀，安岡稔弘，竹川忠克，名倉義行，小林陽一，吉田治典，宮田征門：季間蓄熱機能を有する空調システムのシミュレーションを利用したコミッショニング，第1報 土壌蓄熱空調システムの開発と初期性能評価，空気調和衛生工学会論文集, No.149 , pp.1-9，2009. 8
. M. Miyata, H. Yoshida, T. Iwata, Z. Zhang, Y. Tanabe, T. Yanagisawa: Application and Verification of Energy Baseline Estimation Method by Simulation, Building Simulation, pp.1968-1974, 2007.9
. M. Miyata, H. Yoshida, T. Yasuoka, T. Takegawa, Y. Nagura, Y. Kobayashi, J. Kim: Optimal Operation for HVAC System with Seasonal Underground Thermal Storage System, Building Simulation, pp.1991-1998, 2007.9
. 宮田征門，吉田治典，浅田昌彦，岩田卓郎，田邊陽一，柳澤忠宏：実ESCOプロジェクトにおけるベースライン簡易補正手法の比較検討，空気調和・衛生工学会論文集，pp.7-16，No.119，2007. 2
. M. Miyata, H. Yoshida, M. Asada, T. Iwata, Y. Tanabe, T. Yanagisawa: Estimation of Energy Baseline by Simulation for On-going Commissioning and Energy Saving Retrofit, Journal of Harbin Institute of Technology, vol.13, pp.370-378, 2006.11
. H. Yamaguchi, M. Miyata, H. Oda, M. Shioya, T. Watanabe, H. Niwa, H. Yoshida: Experimental Study of a Cooling Coil and the Validation of its Simulation Model for the Purpose of Commissioning, Journal of Harbin Institute of Technology, Vol. 13, pp.385-392, 2006.11
. 宮田征門，吉田治典，浅田昌彦，橋口士朗：コミッショニングのための複数VAVユニットの不具合検知・診断手法，空気調和・衛生工学会論文集，pp.1～9，No.114，2006. 9
. M. Miyata, H. Yoshida, M. Asada, K. Fujii, S. Hashiguchi: Estimation of Excessive HVAC Energy Consumption due to faulty VAV units, Building Simulation, pp.777-786, 2005.8
. F. Wang, H. Yoshida, M. Miyata: Total Energy Consumption Model of Fan Subsystem Suitable for Continuous Commissioning, ASHRAE Transactions, Vol. 110, pp. 357-364, 2004

==== 国際会議論文
. Masato Miyata: Energy Efficiency Evaluation of Multiple Split-System Air Conditioners with Unbalanced Load Operation for Building Energy Simulation, The 4th Asia Conference on International Building Performance Simulation Association, 2018
. Ken Fukada, Masato Miyata: Validation of Unsteady CFD Considering Thermal Load Fluctuation in Office Room, The 4th Asia Conference on International Building Performance Simulation Association, 2018
. Tatsuhito Itou, Daisuke Sumiyoshi, Mikiko Nakamura, Hiroaki Okamoto, Masato Miyata, Yasuo Kuwasawa: Study on Improvement of Energy Performance Evaluation Method about Cogeneration Systems for Buildings, The 4th Asia Conference on International Building Performance Simulation Association, 2018
. M. Miyata、他5名: Web-based Simulation Tool for the 2013 Energy Efficiency Standard for Commercial Buildings in Japan, The 2nd Asia Conference on International Building Performance Simulation Association, 2014
. E. Tanaka, M. Mukai, K. Matusako, Y. Kodera, S. Maeda, Y. Akashi, H. Yoda, T. Watanabe, M. Miyata: Development of Database for Energy Consumption of Non-residential Buildings in Kyushu, the Proceedings of the Yellow Sea Rim International Exchange Meeting on Building Environment and Energy 2009, pp.79-86, 2009. 1
. M. Miyata, H. Yoshida, M. Aono, T. Yasuoka, T. Takegawa, Y. Nagura, Y. Kobayashi, J. Kim: On-going Commissioning of HVAC System with Seasonal Ground Thermal Storage Using Simulation, the Proceedings of the Yellow Sea Rim International Exchange Meeting on Building Environment and Energy 2009, pp.143-154, 2009. 1
. M. Miyata, H. Yoshida, H. Yoshida: Development of an Information Flow Mechanism for Commissioning, International Conference for Enhanced Building Operations, No. 8, pp. 55(1)-55(8), 2008.10
. M. Miyata, H. Yoshida, T. Yasuoka, T. Takegawa, Y. Nagura, Y. Kobayashi, J. Kim: Development of a Simulation Tool for the Commissioning of a HVAC system with Seasonal Thermal Storage, National conference on Building Commissioning, Chicago, 2007.5
. M. Miyata, H. Yoshida, M. Asada, F. Wang, S. Hashiguchi: Fault Detection and Diagnosis Method for VAV Terminal Units, International Conference of Enhanced Building Operation, PF-52, 2004.10
. M. Miyata, F. Wang, H. Yoshida, M. Tsubaki, K. Itou: Experimental Study on Model-based Commissioning Method of VAV Systems in a Real Building, International Conference of Enhanced Building Operation, 2003.10

==== 学内報
. 姜信愛，赤司泰義，宮田征門，小塩真奈美，浦山真一：建物空調システム設計が運用時のエネルギー消費量に与える影響，九州大学大学院人間環境学研究院紀要，No.17， pp.55-62，2010. 1
. 李霽憲，赤司泰義，住吉大輔，宮田征門，松下直幹：熱源システムのリアルタイム運転最適化手法の開発と実建物への適用，都市・建築学研究　九州大学大学院人間環境学研究院紀要，No.15， pp.103-110， 2009. 1

==== 公開研究資料
. 建築研究資料第187号: 建築物の設備・機器のエネルギー効率に関する既存試験方法の調査, H29.09
. 国総研資料第974号, 建築研究資料第183号: 平成28年省エネルギー基準（平成28年1月公布）関係技術資料 モデル建物法入力支援ツール解説, H29.06
. 国総研資料第973号, 建築研究資料第182号: 平成28年省エネルギー基準（平成28年1月公布）関係技術資料 エネルギー消費計算プログラム（非住宅版）解説, H29.06
. 建築研究資料第177号: 業務用空調・給湯システムの制御による省エネルギー効果の実証的評価 H28.11
. 建築研究資料第176号: 業務用建築物のエネルギー消費量評価手法に関する基礎的調査, H28.11
. 国総研プロジェクト研究報告第53号: 電力依存度低減に資する建築物の評価・設計技術の開発, H28.11
. 建築研究資料第164号: 住宅･建築物省CO2先導事業全般部門(平成22年度～24年度)における採択事例の評価分析, H27.02
. 国総研資料第764号, 建築研究資料第151号: 平成25年省エネルギー基準(平成25年9月公布)等関係技術資料 主要室入力法による非住宅建築物の一次エネルギー消費量算定プログラム解説, H25.11
. 国総研資料第763号, 建築研究資料第150号: 平成25年省エネルギー基準(平成25年9月公布)等関係技術資料 非住宅建築物の外皮性能評価プログラム解説, H25.11
. 国総研資料第762号, 建築研究資料第149号: 平成25年省エネルギー基準(平成25年9月公布)等関係技術資料 一次エネルギー消費量算定プログラム解説(非住宅建築物編), H25.11
. 国総研資料第702号, 建築研究資料第140号: 低炭素建築物認定基準(平成24年12月公布)等関係技術資料 一次エネルギー消費量算定プログラム解説(建築物編), H24.12



==== 口頭発表

. 宮田征門，吉田治典，松岡一平：空調二次側システムのモデルベース性能検証手法に関する研究，日本建築学会近畿支部研究報告集，第43号，環境系，pp.365-368，2003.6
. 宮田征門，吉田治典，松岡一平：空調二次側システムのモデルベース検証法，空気調和・衛生工学会学術講演会論文集，pp.1249-1252，2003.9
. 浅田昌彦，吉田治典，宮田征門：実事務所建物におけるVAVシステムの不具合検知・診断手法に関する研究，（第1報）スミルノフ・グラブス検定を用いた不具合判定手法，日本建築学会近畿支部研究報告集，第44号，環境系，pp.265-268，2004.6.
. 宮田征門，吉田治典，浅田昌彦：実事務所ビルにおけるVAV システムの不具合検知・診断手法に関する研究，(第2報)　実運転データを用いた不具合検知・診断手法の結果，日本建築学会近畿支部研究報告集，第44号，環境系，pp.269-272，2004.6
. 浅田昌彦，吉田治典，宮田征門：VAVシステムの不具合検知・診断手法に関する研究，日本建築学会大会学術講演梗概集，D2，pp.1457-1458，2004.8
. 宮田征門，吉田治典，浅田昌彦：大規模建物におけるVAV ユニットの不具合検知・診断手法に関する研究，(第1報)　安定運転時データを用いた不具合検知・診断手法の提案と実証，空気調和・衛生工学会学術講演会論文集，pp.827-830，2004.9
. 浅田昌彦，吉田治典，宮田征門：大規模建物におけるVAV ユニットの不具合検知・診断手法に関する研究，(第2報)　予冷時データを用いた不具合検知・診断手法の提案と実証，空気調和・衛生工学会学術講演会論文集，pp.831-834，2004.9
. 宮田征門，吉田治典，浅田昌彦，橋口士朗：VAVユニットの不具合がシステム全体のエネルギー消費量に与える影響に関する研究，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp169-172，2005.3
. 浅田昌彦，吉田治典，宮田征門：実建物におけるVAVユニットの不具合検知・診断手法に関する研究，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp.173-176，2005.3
. 浅田昌彦，吉田治典，宮田征門：ＶＡＶユニットの不具合がシステム全体のエネルギー消費量に与える影響に関する研究，（第１報）　実験室実験によるエネルギー浪費の分析，日本建築学会近畿支部研究報告集，第45号，環境系，pp.325-328，2005.6
. 宮田征門，吉田治典，浅田昌彦：VAVユニットの不具合がシステム全体のエネルギー消費量に与える影響に関する研究，（第２報）シミュレーションによるエネルギー浪費量の推定，日本建築学会近畿支部研究報告集，第45号，環境系，pp.329-332，2005.6
. 宮田征門，吉田治典，藤井健太，浅田昌彦，VAVユニットの不具合によるエネルギー浪費の推定手法に関する，日本建築学会大会学術講演梗概集，pp.33-36，2005.9
. 岩田卓郎，浅田昌彦，宮田征門，吉田治典，田邊陽一，柳澤忠宏，シミュレーションによるエネルギーベースライン推定手法（第一報）熱負荷によるエネルギー消費量の推定，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp.29-32，2006.3
. 浅田昌彦，岩田卓郎，宮田征門，吉田治典，田邊陽一，柳澤忠宏，シミュレーションによるエネルギーベースライン推定手法（第二報）ベースライン推定モデルとベースライン推定式の作成，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp.33-36，2006.3
. 宮田征門，吉田治典，山下健太郎，安岡稔弘，竹川忠克，名倉義行，小林陽一，金政秀：土壌蓄熱を有する空調システムの性能分析，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp.37-40，2006.3
. 岩田卓郎，吉田治典，宮田征門，浅田昌彦：ESCOのためのシミュレーションによるベースライン補正手法，（第１報）　熱負荷によるエネルギー浪費量の推定，日本建築学会近畿支部研究報告集，第46号，環境系，pp.317-320，2006.6
. 宮田征門，吉田治典，浅田昌彦，岩田卓郎：ESCOのためのシミュレーションによるベースライン補正手法，（第２報）　ベースライン推定モデルによるベースライン補正式の作成，日本建築学会近畿支部研究報告集，第46号，環境系， pp.321-324，2006.6
. 竹川忠克, 安岡稔弘, 名倉義行, 小林陽一, 金政秀，吉田治典，宮田征門：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その１）システム概要および実測結果，空気調和・衛生工学大会論文集，pp.263-266，2006.9
. 宮田征門，吉田治典，安岡稔弘，竹川忠克，名倉義行，小林陽一，金政秀，杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その２）シミュレーションによるシステム運転方法の検討，空気調和・衛生工学大会論文集，pp.267-270，2006.9
. 岩田卓郎，吉田治典，宮田征門，田邊陽一，柳澤忠宏，シミュレーションによるエネルギーベースライン推定手法，空気調和・衛生工学大会論文集，pp.707-710．2006.9
. 小田久人，山口弘雅，宮田征門，塩谷正樹，渡邉剛，丹羽英治，吉田治典，コミッショニングのためのコイル特性実験とモデル精度の検証，空気調和・衛生工学大会論文集，pp.1669-1672，2006.9
. 安岡稔弘, 竹川忠克, 名倉義行, 小林陽一,金政秀: 杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その１）システム概要および実測結果，日本建築学会大会学術講演梗概集，D2，pp.1299-1300，2006.9
. 宮田征門，吉田治典，安岡稔弘，竹川忠克，名倉義行，小林 陽一，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その２） シミュレーションによるシステムの運転方法の検討，日本建築学会大会学術講演梗概集，D2，pp1301-1302，2006. 9
. 李博，吉田治典，宮田征門，安岡稔弘，竹川忠克，名倉義行，小林陽一，金政秀，杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの性能分析，（その１）空調システムの性能検証実験とモデル化，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp.73-76，2007.3
. 宮田征門，吉田治典，李博，安岡稔弘，竹川忠克，名倉義行，小林陽一，金政秀，杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの性能分析，（その２）シミュレーションによるシステムの運転方法の検討，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp.77-80，2007.3
. 張兆明，吉田治典，宮田征門，岩田卓郎，田邊陽一，柳澤忠宏，実建物を用いたシミュレーションによるベースライン推定手法の検証，空気調和・衛生工学会近畿支部学術研究発表会論文集，pp.81-84．2007.3
. 青野政信，竹川忠克，名倉義行，小林 陽一，金政秀，吉田治典，宮田征門，李博：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その３）運転実績の評価および性能分析，日本建築学会大会学術講演梗概集，D2，pp. 1213～1214，2007.8
. 李博，吉田治典，宮田征門，青野政信，竹川忠克，名倉義行，小林 陽一，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その４） 空調システム機器モデルの構築と検証，日本建築学会大会学術講演梗概集，D2，pp. 1215～1216，2007.8
. 宮田征門，吉田治典，李博，青野政信，竹川忠克，名倉義行，小林 陽一，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その５） シミュレーションによるシステム運転法の最適化，日本建築学会大会学術講演梗概集，D2，pp. 1217～1218，2007.8
. 宮田征門，吉田治典，李博，青野政信，竹川忠克，名倉義行，小林陽一，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの性能分析，（その３）冷却塔ファンのインバータ化に伴う運転の最適化，空気調和・衛生工学会学術講演論文集，pp.1761-1764，2007.9
. 竹川忠克，青野政信，名倉義行，小林陽一，金政秀，宮田征門，吉田治典，李博：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの性能分析，（その４）運転実績の評価および性能分析，空気調和・衛生工学会学術講演論文集，pp.1765-1768，2007.9
. 岩田卓郎,吉田治典,張兆明,宮田征門:実建物を用いたシミュレーションによるベースライン推定法 (第一報)　推定法検証のための実建物における実験，空気調和・衛生工学会学術講演論文集，pp.2273-2276，2007.9
. 張兆明,吉田治典,岩田卓郎,宮田征門:実建物を用いたシミュレーションによるベースライン推定法 (第二報)　室温と外気取入量に関する検証，空気調和・衛生工学会学術講演論文集，pp.2277-2280，2007.9
. 宮田征門，吉田治典，青野政信，竹川忠克，名倉義行，小林陽一，金政秀:土壌を利用した季間空調システムの性能分析，（その３）シミュレーションによる採熱運転法の最適化とその効果の検証, 空気調和・衛生工学会近畿支部学術研究発表会, pp49-52, 2008. 3
. 岩田卓郎，吉田治典，宮田征門：熱負荷計算を用いた補正ベースライン推定モデルの構築法に関する研究, 空気調和・衛生工学会近畿支部学術研究発表会, pp53-56, 2008. 3
. 青野政信,竹川忠克, 名倉義行, 小林陽一,金政秀, 吉田治典, 宮田征門: 杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析, （その２）運転実績の評価および性能分析, 第42回空気調和・冷凍連合講演会, 2008.4
. 宮田征門，吉田治典，青野政信，竹川忠克，名倉義行，小林陽一，金政秀: 地盤を利用した季間蓄熱機能を有する空調システムの運転最適化, 空気調和・衛生工学会九州支部学術研究発表会, pp19-24, 2008. 5
. 宮田征門，吉田治典，青野政信，竹川忠克，名倉義行，小林陽一，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その５）シミュレーションによる採熱運転法の最適化とその効果の検証，空気調和・衛生工学会学術講演論文集，pp.857-860，2008.8
. 竹川忠克，青野政信，名倉義行，小林陽一，吉田治典，宮田征門，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その６）他施設への適用を仮定した効果検証，空気調和・衛生工学会学術講演論文集，pp.861-864，2008.8
. 福崎達也，赤司泰義，住吉大輔，宮田征門，桑原康浩，村澤達，上田憲治：高効率化技術を導入した熱源システムの性能評価，（その１）実測結果に基づく性能評価，空気調和・衛生工学会学術講演論文集，pp.1623-1626，2008.8
. 張兆明，吉田治典，宮田征門，新宮浩丈，山下植也，田代博一：シミュレーションを用いた空調用例熱源の最適運転設計と運転に関する研究，空気調和・衛生工学会学術講演論文集，pp.1663-1666，2008.8
. 大曲康仁，吉田治典，宮田征門，三枝隆晴：シミュレーションを用いたVAVシステムの給気温度設定値の最適化，空気調和・衛生工学会学術講演論文集，pp.2199-2202，2008.8
. 吉田泰基，吉田治典，宮田征門：コミッショニングのための情報フロー統合メカニズムに関する研究，日本建築学会大会学術講演梗概集, 選抜梗概, pp.1011-1014, 2008.9
. 宮田征門，吉田治典，青野政信，竹川忠克，名倉義行，小林陽一，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その６）シミュレーションによる採熱運転法の最適化とその効果の検証，日本建築学会大会学術講演梗概集, pp.1101-1102, 2008.9
. 竹川忠克，青野政信，名倉義行，小林陽一，吉田治典，宮田征門，金政秀：杭基礎を利用した自然エネルギーによる土壌蓄熱空調システムの分析，（その７）他施設への適用を仮定した効果検証，日本建築学会大会学術講演梗概集, pp.1103-1104, 2008.9
. 宮田征門，赤司泰義，末吉祥平：建物とのインタラクションを考慮した空調システムの最適運転制御法，日本建築学会大会学術講演梗概集, pp.1083-1084, 2009.8
. 宮田征門，吉田治典，辻忠男，湯川求，大川和伸，今井和哉：業務用建築物のためのエネルギー消費量評価手法に関する調査研究（その5）個別分散型空調システムの実稼働状態における入出力特性計測手法に関する検討，空気調和・衛生工学会学術講演論文集，pp.1759-1762，2010.9
. 宮田征門，足永靖信，澤地孝男，桑沢保夫，秦良昌，三浦尚志：低炭素コミュニティ形成のための水素エネルギー活用技術に関する研究（第3報）省エネルギー・省CO2 効果の評価，空気調和・衛生工学会学術講演論文集，pp.197-200，2010.9
. 宮田征門，吉田治典，澤地孝男，桑沢保夫：個別分散型空調システムの実稼働状態における入出力特性計測手法に関する検討，日本建築学会大会学術講演梗概集, pp.1025-1026, 2010.9
. 宮田征門，吉田治典，澤地孝男，桑沢保夫：個別分散型空調システムの運用段階における実性能とJIS 試験法による性能の比較，日本建築学会大会学術講演梗概集, pp.1265-1266, 2011.8
. 宮田征門，澤地孝男，斉藤正文，梅主洋一郎，川瀬貴晴，坂本雄三：業務用建築の年間空調エネルギー消費量簡略計算法の開発，（その４）室負荷から空調システムのエネルギー消費量を推定する手法の枠組み，空気調和・衛生工学会学術講演論文集，pp.2445-2448，2011.9
. 小寺優貴・赤司泰義・宮田征門・依田浩敏・前田昌一郎・渡辺俊行・村上周三・亀谷茂樹・半澤久・吉野博・下田吉之・村川三郎：非住宅（民生業務部門）建築物の環境関連データベース構築に関する研究, (その23) 標準（レベル２）データベース解析結果（平成19年度調査）	
. 依田浩敏・田中絵梨香・赤司泰義・宮田征門・前田昌一郎・渡辺俊行：非住宅（民生業務部門）建築物の環境関連データベース構築に関する研究, (その34)九州における調査建物概要と省エネルギー対策（平成20年度調査）, 
. 田中絵梨香・依田浩敏・赤司泰義・宮田征門・前田昌一郎・渡辺俊行：非住宅（民生業務部門）建築物の環境関連データベース構築に関する研究, その35 九州におけるエネルギー・水消費量の実態（平成20年度調査）, 
. 田中絵梨香・依田浩敏・前田昌一郎・赤司泰義・渡辺俊行・宮田征門：九州地域における非住宅建築物の環境関連データベースの構築に関する研究　その３　平成20年度調査における調査建物概要とエネルギー・水消費量の実態
. 小寺優貴・赤司泰義・宮田征門・依田浩敏・前田昌一郎・渡辺俊行・村上周三・亀谷茂樹・半澤久・吉野博・下田吉之・村川三郎：民生業務用建築物の年間エネルギー消費原単位の推定
. 宮田征門、吉田治典、澤地孝男、桑沢保夫：個別分散型空調システムの運用段階における実性能とJIS 試験法による性能の比較、日本建築学会大会学術講演梗概集、pp.1265-1266、2011
. 吉田治典、宮田征門、他2名：新たな省エネ基準策定のための建築設備の使用実態とエネルギー消費実態に関する調査研究、（その4）個別分散型空調システムの入出力特性に関する実態調査、空気調和・衛生工学会学術講演論文集、pp.2405-2408、2011
. 阿部靖則、宮田征門（10番目）、他8名：空調システム、給湯システムの各種制御手法におけるエネルギー削減効果の実態調査、（その1）〜（その5）、空気調和・衛生工学会学術講演論文集、 pp.1399-1418、2012
. 宮田征門、青山博昌、他3名：個別分散型空調システムの室内機千鳥配置による省エネルギー効果、空気調和・衛生工学会学術講演論文集、第3巻、pp.113-116、2013
. 野田昂志、吉田治典、宮田征門、他3名：ACSES/Cxを用いた空調2次側ポンプ群の台数制御による省エネルギー効果に関する研究、空気調和・衛生工学会学術講演論文集、第8巻、pp.121-124、2013
. M. Miyata、他4名: Improvement of Energy Efficiency of VRF systems through Staggered Arrangement of indoor units in Heating Mode、空気調和・衛生工学会学術講演論文集、第3巻、pp.249-252、2014
. 宮田征門、他4名：建築物の室内負荷の偏在がビル用マルチパッケージ型空調システムの運転効率に与える影響の解明、日本冷凍空調学会年次大会梗概集、B132-1-4、2015
. 宮田征門、足永靖信：建築物の電力ピーク対策評価システムの開発、日本建築学会大会学術講演梗概集、p.1201-1202、2016

=== 雑誌等寄稿
. 宮田征門：非住宅建築物の省エネルギー基準の改正、空気調和衛生工学、第87巻第12号、pp.14-21、2013
. 宮田征門：建築物の省エネルギー基準の見直し、一次エネルギー消費量の算出方法について、BE建築設備、一般社団法人建築設備総合協会、第751号、pp.14-21、2013
. 宮田征門：建築物における改正基準の概要、計算のフロー、建築環境省エネルギー機構　機関誌IBEC、Vol33-6、No195、pp.39-44、2013
. 宮田征門：一次エネルギー消費量算定プログラムについて、建築環境省エネルギー機構　機関誌IBEC、Vol33-6、No195、pp.53-54、2013
. 宮田征門：自立循環プロジェクト（フェーズ4）における業務用建築物を対象とした研究の方向性について、建築環境省エネルギー機構　機関誌IBEC、Vol33-4、No193、pp.58-59、2013
. 宮田征門：建築の改正省エネルギー基準と設計への応用：空気調和設備の計算の導き方、建築技術 No.775、pp.96-103、2014
. 宮田征門：改正省エネルギー基準を省エネ設計に活用する（一次エネルギー消費量）、建築技術 No.775、 pp.122-125、2014
. 宮田征門：建築環境設計におけるエネルギーシミュレーションの活用、建築技術 No.786、pp.162-165、2015
. 宮田征門：「エネルギー消費性能計算プログラム」を活用した設計プロセス、BE建築設備No.789、pp.25-31、2016
. 宮田征門：基準適合性判定プログラム（非住宅建築物）の開発趣旨、BE建築設備 No.780、pp.14-18、2016

=== 出版物
. 平成25年省エネルギー基準に準拠した算定・判断の方法及び解説(I.非住宅建築物)、国総研・建研監修、連合印刷センター出版、2013
. 平成25年省エネルギー基準に準拠した算定・判断の方法及び解説(I.非住宅建築物、第二版)、国土技術政策総合研究所・建築研究所監修、連合印刷センター出版、2014

=== 依頼/招待講演・講義
. 建築設備技術者協会 講習会 '取り組んでみた省エネ手法': ビルの新しい省エネルギー 判断基準の策定にむけて - 空調システムのエネルギー消費量 簡略計算法の概要, 2011.10.26
. 建築設備コミッショニング協会 東京講演会: ビルの新しい省エネルギー判断基準の策定に向けて, 2011.5.19
. 空気調和・衛生工学会近畿支部一般講習会（平成24年度）: 建築物の省エネルギー施策の動向と新たな省エネルギー基準の概要,2012.12.4
. TSC21 オープンセミナー2012 vol.2 'エネルギー施策とマネジメントの動向': 建築物の省エネルギー施策の動向と新たな省エネルギー基準の概要, 2012.12.6
. 空気調和・衛生工学会九州支部講習会'建築物の省エネルギーに関する施策と基準の最新動向': 非住宅建築物の省エネルギー基準の概要, 2013.2.27
. つくば市立手代木南小学校（出前講座）: 住まいで使うエネルギー, 2013.7.26
. 空気調和・衛生工学会コミッショニングシンポジウム特別講演：省エネ基準の見直しの概要とコミッショニングの役割, 2013.8.9
. 一般財団法人建築環境・省エネルギー機構 主催：平成25年度省エネルギー基準の「算定・判断方法に係る根拠・理論」の説明会, 2013.10.23（大阪）, 2013.10.30（東京）
. 空気調和・衛生工学会近畿支部一般講習会（平成25年度）: 省エネルギー法・新たな建築物省エネ基準の本格運用に向けて, 2013.11.21
. つくばエキスポセンター ミニ講演: 住まいで使うエネルギーについて, 2013.11.23
. 群馬県設備設計事務所協会 技術研修会: 改正省エネルギー基準（非住宅建築物）の概要と今後の展開, 2014.3.7
. 一般財団法人建築環境・省エネルギー機構 主催：平成26年度省エネルギー基準の「算定・判断方法に係る根拠・理論」の説明会, 2014.9.25（東京）, 2014.10.3（大阪）
. 一般財団法人建築環境・省エネルギー機構 主催：平成26年度建築物の建築物の省エネルギー基準講習会, 2015.1.20（東京）, 2015.2.4（東京）, 2015.2.20（福岡）
. 工学院大学 建築学部まちづくり学科 建築学特別講義 2015年度：究極の省エネルギー建築物を設計するために必要な3つのこと, 2015.6.5
. 一般社団法人関西ESCO協会 特別講演会: 住宅・建築物の省エネ化に関する施策の最新情報と今後の展開, 2015.6.8
. 東京大学 建築環境特論 2015〜2017年度: 究極の省エネルギー建築物を設計するために必要な3つのこと, 2015.7.10, 2016.5.13, 2017.5.12
. 日本設備設計事務所協会 設備設計セミナー: 新法「建築物省エネ基準」の概要 ~ 建築確認申請における性能判定について ~, 2015.10.7
. HVAC&R JAPAN 2016: いよいよ始まる建築物省エネ基準の適合義務化 ~ 建築確認申請における 設備機器の性能確認について ~, 2016.2.24
. 平成27年度第2回地中熱利用シンポジウム: 省エネ基準適合義務化の背景と地中熱への期待, 2016.3.10
. 建築環境設計支援協会 CFDシンポジウム: 建築物の省エネルギー基準と建築環境シミュレーション (エネルギーシミュレーション), 2016.5.18, 2016.11.30
. 地中熱利用促進協会 地中熱利用にかかる省エネ基準説明会: 省エネ基準適合義務化の概要と地中熱ヒートポンプの評価法, 2016.12.16
. 中部地中熱利用促進協議会地中熱設計セミナー: 省エネ基準適合義務化の概要と地中熱ヒートポンプの評価法, 2017.2.10
. ENEX2017 地中熱セミナー: 省エネ基準適合義務化の概要と地中熱ヒートポンプの評価法, 2017.2.17
. 長野県地中熱利用促進協議会: 省エネ基準適合義務化の概要と地中熱ヒートポンプの評価法, 2017.6.21
. 放射(輻射)冷暖房協議会・ASHRAE JAPAN Chapter 共催セミナー: 省エネ基準適合義務化の施行状況と今後のビジョン, 2017.9.11
. 一般財団法人建築環境・省エネルギー機構 主催：平成27年度省エネルギー基準の「算定・判断方法に係る根拠・理論」の説明会, H27.7.17（東京）, H27.7.30（大阪）
. 第31回公衆衛生情報研究協議会研究会: 適合義務化された建築物省エネルギー基準の現状と今後の展開, 2018.1.25
. 第26回地中熱利用シンポジウム: 建築物省エネルギー基準における地中熱利用ヒートポンプの評価法, 2018.3.14
. イオンリテール イオン下妻店（出前講座） : たてものでつかう エネルギー, 2018.8.6
. 東京大学 環境調整工学特論 2018年度： 建築物のエネルギー消費性能の定量的評価, 2018.6.26
. 一般財団法人建築環境・省エネルギー機構 主催：建築物省エネ法に関する算定ロジックと計算事例解説, 2018.11.16（東京）, 2018.12.19（東京）





=== 委員会活動

. 空気調和衛生工学会 コミッショニング委員会
. 日本建築学会 学会誌編集委員会 委員, 2016-2017
. ISO/TC205/WG10 Commissioning Convenor (第一期: 2014-2017) (第二期: 2017-2021)

=== 委員等



